### ISSUE TITLE
column name links broken in 0.50.1

### ISSUE THREAD

**Issue by mhalle** [simonw/datasette#1011]
I just upgraded from 0.49 to 0.50.1 and found that the links on column headers are broken. 

If I inspect the source, they have a leading "//" (without host or port) rather than including base_url like other links on the page do. The links in the "gears" menu for each column do work.

 I don't have custom templates for my project.

**Comment by simonw** [comment]
Oh no! It's the same bug as #1010. Thanks for the report, I shall push out 0.50.2 as quickly as possible.

**Comment by simonw** [comment]
Demo: click column headers on https://latest.datasette.io/fixtures/compound_three_primary_keys

**Comment by simonw** [comment]
The fix is live on the demo: https://latest.datasette.io/fixtures/compound_three_primary_keys?_sort_desc=pk2

**Comment by simonw** [comment]
OK, Datasette 0.50.2 is live on PyPI now.
