### ISSUE TITLE
datasette.urls.static_plugins(...) method

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#1033]
Follow-on from #904. For constructing URLs like this:

    /-/static-plugins/NAME_OF_PLUGIN_PACKAGE/yourfile.js

Should be documented on https://docs.datasette.io/en/latest/writing_plugins.html#static-assets and https://docs.datasette.io/en/latest/internals.html#datasette-urls

**Comment by simonw** [comment]
Also refs #1023

**Comment by psychemedia** [comment]
How does `/-/static` relate to [current guidance docs around `static`](https://docs.datasette.io/en/latest/custom_templates.html?highlight=static#serving-static-files) regarding the `--static option` and metadata formulations such as `"extra_js_urls": [ "/static/app.js"]` (I've not managed to get this to work in a Jupyter server proxied set up; the [datasette / jupyter server proxy repo](https://github.com/simonw/jupyterserverproxy-datasette-demo) may provide a useful test example, eg via MyBinder, for folk to crib from?)

**Comment by simonw** [comment]
That's a good question - I hadn't considered that. I'm going to open a new issue to have `extra_js_urls` respect the `base_url` setting, since the static files will be served from a different location.

**Comment by simonw** [comment]
Documentation here: https://docs.datasette.io/en/latest/internals.html#datasette-urls

**Comment by psychemedia** [comment]
From [the docs](https://docs.datasette.io/en/latest/internals.html#datasette-urls), I note:

```
datasette.urls.instance()
Returns the URL to the Datasette instance root page. This is usually "/"
```

What about the proxy case? Eg if I am using jupyter-server-proxy on a MyBinder or local Jupyter notebook server site, `https://example.com:PORT/weirdpath/datasette`, what does `datasette.urls.instance()` refer to?

- [ ] `https://example.com:PORT/weirdpath/datasette`
- [ ] `https://example.com:PORT/weirdpath/`
- [ ] `https://example.com:PORT/`
- [ ] `https://example.com`
- [ ] something else?
