### ISSUE TITLE
Switch to .blob render extension for BLOB downloads

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#1050]
This may require a complete rethink of the `/db/table/-/blob/row/column.blob` mechanism I just built for #1036.

**Comment by simonw** [comment]
Idea: `.blob` output rendererer, where you tell it which column you want using `?_column=x`.

**Comment by simonw** [comment]
This is clearly a better solution than the one I  implemented in #1040 - I don't have to add a new route, I don't have to implement permission checks, it reuses mechanism.

**Comment by thadk** [comment]
Unsolicited feedback for an unreleased feature of the [current](https://github.com/simonw/datasette/commit/5e0b72247ecab4ce0fcec599b77a83d73a480872) unreleased GitHub version (I casually wanted to access a blob row) – the existing #1036 route doesn't support special characters in database or table names (e.g. `@()` )

Also I got this error/crash with my blob and wasn't able to get it: https://gist.github.com/thadk/28ac32af0e88747ce9056c90b0b19d34

**Comment by simonw** [comment]
@thadk from that error it looks like the problem may have been that you had a BLOB column containing a `null` value? If so that's definitely a bug, I'll fix that.

**Comment by simonw** [comment]
Yes, confirmed - this is a bug where if the `BLOB` column contains a `null` you get a nasty exception if you try to download it.

**Comment by simonw** [comment]
Had an idea in https://github.com/simonw/datasette/issues/1051#issuecomment-718980659

> OK, alternative idea. The `.blob` output renderer from #1050 gets to see multiple rows at once.
> 
> For an arbitrary SQL query, how about if I link to this?
> 
> `/db.blob?sql=...&_blob_column=data&_blob_hash=bc4c24181ed3ce666`
> 
> Then the output renderer loops through all of the `data` results that are available to it and, if one of them hashes to that value, serves up that data?
> 
> If no matches are found it can show an error message telling you that the link has expired (presumably because the underlying database has changed since the link was generated).
> 
> I think this might be the best solution to the problem.

**Comment by simonw** [comment]
The reason I like the `?_blob_hash=` solution is that it feels really misleading to provide a link to "download this binary" which could conceivably download some other data.

**Comment by simonw** [comment]
I'll use `hashlib.sha256` for these hashes.

**Comment by simonw** [comment]
I'll do the rest of the work on this in the pull request #1061.

**Comment by simonw** [comment]
Idea: what if Datasette had a custom SQLite function that could be used to generate URLs to the row-level BLOB download for a value? Then custom SQL query authors could use that function to link to the relevant content.

This could be expanded to exposing other `datasette.urls` functionality as well.
