### ISSUE TITLE
.json and .csv exports fail to apply base_url

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#1091]
> Just tested with the latest Docker image, and it works pretty much everywhere!  THANK YOU!
> 
> I did notice that if I try to export json or csv, the base is not applied.  Not sure if I should reopen this issue or open a new one.
> 
> To see this, go here: https://corpora.tika.apache.org/datasette/corpora-metadata/REF_PARSE_EXCEPTION_TYPES
> 
> Click/hover over json or CSV and you'll see that the 'datasette' base is not included.

_Originally posted by @tballison in https://github.com/simonw/datasette/issues/865#issuecomment-726385422_

**Comment by simonw** [comment]
Hmm... it's not just the `.csv` and `.json` export links - it's the column headings (which can be clicked to change the sort order) as well. Here's an extract of the HTML from that page:
```html


<p class="export-links">This data as 
	<a href="/corpora-metadata/REF_PARSE_EXCEPTION_TYPES.json">json</a>, 
	<a href="/corpora-metadata/REF_PARSE_EXCEPTION_TYPES.csv?_size=max">CSV</a> (
	<a href="#export">advanced</a>)
</p>
<div class="table-wrapper">
	<table class="rows-and-columns">
		<thead>
			<tr>
				<th class="col-Link" scope="col" data-column="Link" data-column-type="" data-column-not-null="0" data-is-pk="0">
                        
                            Link
                        
                    </th>
				<th class="col-rowid" scope="col" data-column="rowid" data-column-type="integer" data-column-not-null="0" data-is-pk="1">
					<a href="/corpora-metadata/REF_PARSE_EXCEPTION_TYPES?_sort_desc=rowid" rel="nofollow">rowid&nbsp;▼</a>
				</th>
				<th class="col-PARSE_EXCEPTION_ID" scope="col" data-column="PARSE_EXCEPTION_ID" data-column-type="INTEGER" data-column-not-null="0" data-is-pk="0">
					<a href="/corpora-metadata/REF_PARSE_EXCEPTION_TYPES?_sort=PARSE_EXCEPTION_ID" rel="nofollow">PARSE_EXCEPTION_ID</a>
				</th>
				<th class="col-PARSE_EXCEPTION_DESCRIPTION" scope="col" data-column="PARSE_EXCEPTION_DESCRIPTION" data-column-type="VARCHAR(128)" data-column-not-null="0" data-is-pk="0">
					<a href="/corpora-metadata/REF_PARSE_EXCEPTION_TYPES?_sort=PARSE_EXCEPTION_DESCRIPTION" rel="nofollow">PARSE_EXCEPTION_DESCRIPTION</a>
				</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td class="col-Link type-pk">
					<a href="/datasette/corpora-metadata/REF_PARSE_EXCEPTION_TYPES/1">1</a>
				</td>
				<td class="col-rowid type-int">1</td>
				<td class="col-PARSE_EXCEPTION_ID type-int">0</td>
				<td class="col-PARSE_EXCEPTION_DESCRIPTION type-str">RUNTIME</td>
			</tr>
			<tr>
				<td class="col-Link type-pk">
					<a href="/datasette/corpora-metadata/REF_PARSE_EXCEPTION_TYPES/2">2</a>
				</td>
				<td class="col-rowid type-int">2</td>
				<td class="col-PARSE_EXCEPTION_ID type-int">1</td>
				<td class="col-PARSE_EXCEPTION_DESCRIPTION type-str">ENCRYPTION</td>
			</tr>
			<tr>
				<td class="col-Link type-pk">
					<a href="/datasette/corpora-metadata/REF_PARSE_EXCEPTION_TYPES/3">3</a>
				</td>
				<td class="col-rowid type-int">3</td>
				<td class="col-PARSE_EXCEPTION_ID type-int">2</td>
				<td class="col-PARSE_EXCEPTION_DESCRIPTION type-str">ACCESS_PERMISSION</td>
			</tr>
			<tr>
				<td class="col-Link type-pk">
					<a href="/datasette/corpora-metadata/REF_PARSE_EXCEPTION_TYPES/4">4</a>
				</td>
				<td class="col-rowid type-int">4</td>
				<td class="col-PARSE_EXCEPTION_ID type-int">3</td>
				<td class="col-PARSE_EXCEPTION_DESCRIPTION type-str">UNSUPPORTED_VERSION</td>
			</tr>
		</tbody>
	</table>
</div>
<div id="export" class="advanced-export">
	<h3>Advanced export</h3>
	<p>JSON shape:
            
		<a href="/corpora-metadata/REF_PARSE_EXCEPTION_TYPES.json">default</a>,
            
		<a href="/corpora-metadata/REF_PARSE_EXCEPTION_TYPES.json?_shape=array">array</a>,
            
		<a href="/corpora-metadata/REF_PARSE_EXCEPTION_TYPES.json?_shape=array&amp;_nl=on">newline-delimited</a>
	</p>
	<form action="/corpora-metadata/REF_PARSE_EXCEPTION_TYPES.csv" method="get">
		<p>
                CSV options:
                
			<label>
				<input type="checkbox" name="_dl"> download file
				</label>
				<input type="submit" value="Export CSV">
					<input type="hidden" name="_size" value="max">
					</p>
				</form>
			</div>
```
But here's something _really_ weird - the links to the individual rows DO include the `/datasette/` prefix:
```html
<td class="col-Link type-pk">
    <a href="/datasette/corpora-metadata/REF_PARSE_EXCEPTION_TYPES/2">2</a>
</td>
```
The navigation bar on that page is correct too:
```html
<p class="crumbs">
        <a href="/datasette/">home</a> /
        <a href="/datasette/corpora-metadata">corpora-metadata</a>
</p>
```
I've also been unable to replicate this in my own local environment, running `datasette fixtures.db --config base_url:/datasette/`.

**Comment by simonw** [comment]
@tballison is there any chance you're running any custom templates in that installation? I'm really confused as to why I can't replicate the bug.

**Comment by simonw** [comment]
The sort headers are generated by this template code: https://github.com/simonw/datasette/blob/5eb8e9bf250b26e30b017d39a392c33973997656/datasette/templates/_table.html#L11-L15

The export links use this code:

https://github.com/simonw/datasette/blob/5eb8e9bf250b26e30b017d39a392c33973997656/datasette/templates/table.html#L134

https://github.com/simonw/datasette/blob/5eb8e9bf250b26e30b017d39a392c33973997656/datasette/templates/table.html#L180-L201

**Comment by simonw** [comment]
Here's where `url_csv` comes from: https://github.com/simonw/datasette/blob/11eb1e026f3d84cb771f8d6e204939cbaee130cd/datasette/views/base.py#L542-L545

**Comment by tballison** [comment]
I'm starting this with docker like so:

`docker run --name datasette -d -p 8001:8001 -v `pwd`:/mnt datasetteproject/datasette datasette -p 8001 -h 0.0.0.0 /mnt/file_profiles.db --config sql_time_limit_ms:120000 --config max_returned_rows:100000 --config base_url:/datasette/ --config cache_size_kb:50000`

I'm not doing any templating or anything else custom.

Apropos of nothing, I swapped out a simpler db, so this query should now work:

https://corpora.tika.apache.org/datasette/file_profiles?sql=select%0D%0A++*%0D%0Afrom%0D%0A++file_profiles+fp%0D%0Alimit%0D%0A++10

**Comment by tballison** [comment]
My headers aren't clickable/sortable with custom sql, but I think that's by design.

In the default view, https://corpora.tika.apache.org/datasette/file_profiles/file_profiles, ah, y, now I see that the headers should be sortable, but you're right the base_url is not applied.

base_url works with "View and Edit SQL" and with "(advanced)"

As you point out, does not work with the export csv, json, other or with the "Next page" navigational button at the bottom.

**Comment by simonw** [comment]
@tballison could I see the section of your Apache config that configures the proxying to `/datasette/`?

**Comment by simonw** [comment]
I have a hunch that there may be some extra configuration in play here - could Apache itself be rewriting some of the links using [mod_proxy_html](https://httpd.apache.org/docs/2.4/mod/mod_proxy_html.html)?

**Comment by tballison** [comment]
I don't think we are, but I'll check with Maruan.

I think this is the relevant part of our config?

```
  Alias "/base/" "/usr/share/corpora/"
  <Directory "/usr/share/corpora/">
    Options +Indexes -Multiviews
    AllowOverride None
  </Directory>

  ProxyPreserveHost On

  ProxyPass /datasette http://0.0.0.0:8001
  ProxyPassReverse /datasette http://0.0.0.0:8001

</VirtualHost>
```

**Comment by tballison** [comment]
We're using mod_proxy.

**Comment by tballison** [comment]
Anything we can do to help debug this?  Thank you, again!

**Comment by simonw** [comment]
Could you try removing the `ProxyPassReverse /datasette http://0.0.0.0:8001` line?

My hunch is that `ProxyPassReverse` is rewriting some of the links in the HTML (or maybe in the HTTP headers) in a way that breaks things.

Normally you would need ``` to compensate for the underlying application being unable to rewrite its links - but Datasette's `base_url` setting causes Datasette to rewrite all of the links for you, so `ProxyPassReverse` should be unneccessary.

**Comment by tballison** [comment]
I don't think this fixes it:

```grep -R datasette .
./sites-available/000-default.conf:        ProxyPass /datasette http://127.0.0.1:8001/
./sites-available/000-default.conf:        #ProxyPassReverse /datasette http://127.0.0.1:8001/
./sites-available/corpora-le-ssl.conf:  ProxyPass /datasette http://0.0.0.0:8001
./sites-available/corpora-le-ssl.conf:  #ProxyPassReverse /datasette http://0.0.0.0:8001
./sites-enabled/corpora-le-ssl.conf:  ProxyPass /datasette http://0.0.0.0:8001
./sites-enabled/corpora-le-ssl.conf:  #ProxyPassReverse /datasette http://0.0.0.0:8001
```

**Comment by simonw** [comment]
OK that is really weird. I'll have another go at replicating this locally.

**Comment by henry501** [comment]
I found this issue while troubleshooting the same behavior with an nginx reverse proxy. The solution was to make sure I set:

`proxy_pass http://server:8001/baseurl/ 
`
instead of just:

`proxy_pass http://server:8001
`
The custom SQL query and header links are now correct.

**Comment by simonw** [comment]
@tballison I think that's the solution! It looks like you need to use `ProxyPass /datasette http://127.0.0.1:8001/datasette` in your config.

Give that a go and let me know if it fixes it.

**Comment by simonw** [comment]
@henry501 it looks like you spotted a bug in the documentation - I just addressed that, the fix is now live here: https://docs.datasette.io/en/latest/deploying.html#running-datasette-behind-a-proxy

**Comment by tballison** [comment]
+1

Yep!  Fixes it.  If I navigate to https://corpora.tika.apache.org/datasette, I get a 404 (database not found: datasette), but if I navigate to https://corpora.tika.apache.org/datasette/file_profiles/, everything WORKS!

Thank you!

**Comment by simonw** [comment]
Fantastic!

**Comment by henry501** [comment]
Great, really happy I could help! Reverse proxies get tricky.

**Comment by tballison** [comment]
Y, thank you to both of you!
