### ISSUE TITLE
Table actions cog is misaligned

### ISSUE THREAD

**Issue by abdusco** [simonw/datasette#1121]
At the moment it looks like this
https://datasette-graphql-demo.datasette.io/github/repos

![image](https://user-images.githubusercontent.com/3243482/100716533-e6e2d300-33c9-11eb-866e-1e83ba228bf5.png)

Adding a few flex statements fixes the alignment and centers `h1` text and the cog icon vertically.
![image](https://user-images.githubusercontent.com/3243482/100716605-f8c47600-33c9-11eb-8d69-0e37499cf641.png)

**Comment by simonw** [comment]
Demo: https://latest.datasette.io/fixtures?_bot=1

<img width="729" alt="fixtures" src="https://user-images.githubusercontent.com/9599/100950004-43c0b500-34c0-11eb-918c-aa959376461f.png">
