### ISSUE TITLE
Syntax error when adding

### ISSUE THREAD

**Issue by kaihendry** [simonw/datasette#1148]
Works locally:
```
(ins)[hendry@t14s aws-partners]$ sqlite3 partners.db < test.sql
5|{"href":"https://partners.amazonaws.com/partners/001E000000NaBI0IAN","label":"Slalom"}
6|{"href":"https://partners.amazonaws.com/partners/001E000000VHBQIIA5","label":"Accenture"}
7|{"href":"https://partners.amazonaws.com/partners/001E000000Rp588IAB","label":"Druva"}
8|{"href":"https://partners.amazonaws.com/partners/001E0000013FeQXIA0","label":"Palo Alto Networks"}
9|{"href":"https://partners.amazonaws.com/partners/001E000000Rl12lIAB","label":"New Relic"}
10|{"href":"https://partners.amazonaws.com/partners/001E000000NaBHWIA3","label":"Deloitte"}
11|{"href":"https://partners.amazonaws.com/partners/001E000000Rp5GDIAZ","label":"MegazoneCloud"}
12|{"href":"https://partners.amazonaws.com/partners/001E000000NaBHMIA3","label":"iret, Inc."}
(ins)[hendry@t14s aws-partners]$ cat test.sql
select A.launch_rank, A.partner_info from summary A INNER JOIN summary B
    ON A.launch_rank>=B.launch_rank-3 AND A.launch_rank<=B.launch_rank+4
   WHERE B."partner_info" LIKE '%Palo Alto%'
```

Copy the SQL into https://aws-partners-singapore.vercel.app/partners and get syntax error:

![image](https://user-images.githubusercontent.com/765871/102217393-78e4f280-3f17-11eb-9e13-ca79ed62ec34.png)

**Comment by simonw** [comment]
This is a really frustrating bug with Vercel: https://github.com/simonw/datasette-publish-vercel/issues/28

`+` characters in URLs get translated into spaces before they get to Datasette. They know about the bug and said they were working on a fix a few months ago, but looks like it's still a problem.

A workaround is to avoid `+` and use `-` instead - I think this SQL query does the same thing as yours:

https://aws-partners-singapore.vercel.app/partners?sql=select%0D%0A++A.launch_rank%2C%0D%0A++A.partner_info%0D%0Afrom%0D%0A++summary+A%0D%0A++INNER+JOIN+summary+B+ON+A.launch_rank+%3E%3D+B.launch_rank+-+3%0D%0A++AND+A.launch_rank+-4+%3C%3D+B.launch_rank%0D%0AWHERE%0D%0A++B.%22partner_info%22+LIKE+%27%25Palo+Alto%25%27

```sql
select
  A.launch_rank,
  A.partner_info
from
  summary A
  INNER JOIN summary B ON A.launch_rank >= B.launch_rank - 3
  AND A.launch_rank -4 <= B.launch_rank
WHERE
  B."partner_info" LIKE '%Palo Alto%'
```
I've been moving projects from Vercel to Cloud Run when they run into this, but that's not a great situation to be in.

**Comment by simonw** [comment]
I filed a new public bug in their issue tracker here: https://github.com/vercel/vercel/issues/5575
