### ISSUE TITLE
Add Prettier to contributing documentation

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#1167]
Following #1166 - the docs at https://docs.datasette.io/en/stable/contributing.html should include a section about JavaScript, and it should document how to run Prettier.

I run it in VS Code but it can be run on the command-line too:

    npx prettier 'datasette/static/*[!.min].js' --write

**Comment by benpickles** [comment]
Not sure where exactly to put the actual docs (presumably somewhere in [docs/contributing.rst](https://github.com/simonw/datasette/blob/main/docs/contributing.rst)) but I've made a slight change to make it easier to run locally (copying [the approach in excalidraw](https://github.com/excalidraw/excalidraw/blob/ade2565f497243a5e428f4906d8ed80c872fd981/package.json#L90-L94)): https://github.com/simonw/datasette/compare/main...benpickles:prettier-docs

**Comment by simonw** [comment]
Thanks @benpickles, I just merged that in. I'll use it in the documentation.

    # To check code is conformant
    npm run prettier -- --check
    # To fix it if it isn't
    npm run fix

**Comment by simonw** [comment]
New documentation section here (I documented Black as well): https://docs.datasette.io/en/latest/contributing.html#code-formatting
