### ISSUE TITLE
Certain database names results in 404: "Database not found: None"

### ISSUE THREAD

**Issue by jieter** [simonw/datasette#1181]
I have a file named `test-database (1).sqlite`. When requesting the home route `/`, I see datasette is able to read it correctly:

<img width="409" alt="Screenshot 2021-01-07 at 12 54 46" src="https://user-images.githubusercontent.com/1470389/103889964-9442b800-50e7-11eb-9548-fbf10ed3b1ea.png">

However, if I click any of the links, datasette replies with: `Error 404 Database not found: None`

It seems the hash is crucial, as renaming the file to `database (1).sqlite` makes the error go away.

This lines checks for a single dash:
https://github.com/simonw/datasette/blob/97fb10c17dd007a275ab743742e93e932335ad67/datasette/views/base.py#L184

```
$ datasette test-database\ \(1\).sqlite 
INFO:     Started server process [68314]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8001 (Press CTRL+C to quit)
INFO:     127.0.0.1:54043 - "GET /favicon.ico HTTP/1.1" 200 OK
INFO:     127.0.0.1:54043 - "GET / HTTP/1.1" 200 OK
...
INFO:     127.0.0.1:54044 - "GET /favicon.ico HTTP/1.1" 200 OK
INFO:     127.0.0.1:54044 - "GET /test-database (1) HTTP/1.1" 404 Not Found

```
Version:
```
$ datasette --version
datasette, version 0.53
```

**Comment by simonw** [comment]
Yes, that logic is definitely at fault. It looks like it applies `urllib.parse.unquote_plus()` AFTER it's tried to do the `-` hash splitting thing, which is why it's failing here:

https://github.com/simonw/datasette/blob/97fb10c17dd007a275ab743742e93e932335ad67/datasette/views/base.py#L184-L194

**Comment by simonw** [comment]
I'm going to add a unit test that tries a variety of weird database names.

**Comment by simonw** [comment]
Here's the incomplete sketch of a test:

```python
@pytest.mark.parametrize(
    "filename", ["test-database (1).sqlite", "database (1).sqlite"]
)
def test_weird_database_names(ensure_eventloop, tmpdir, filename):
    # https://github.com/simonw/datasette/issues/1181
    runner = CliRunner()
    db_path = str(tmpdir / filename)
    sqlite3.connect(db_path).execute("vacuum")
    result1 = runner.invoke(cli, [db_path, "--get", "/"])
    assert result1.exit_code == 0, result1.output
    homepage_html = result1.output
    assert False
```

**Comment by rayvoelker** [comment]
I wonder if I'm encountering the same bug (or something related). I had previously been using the .csv feature to run queries and then fetch results for the pandas `read_csv()` function, but it seems to have stopped working recently.

https://ilsweb.cincinnatilibrary.org/collection-analysis/collection-analysis/current_collection-3d56dbf.csv?sql=select%0D%0A++*%0D%0Afrom%0D%0A++bib%0D%0Alimit%0D%0A++100&_size=max

Datasette v0.59.4
![image](https://user-images.githubusercontent.com/9308268/146979957-66911877-2cd9-4022-bc76-fd54e4a3a6f7.png)
