### ISSUE TITLE
`datasette publish upload` mechanism for uploading databases to an existing Datasette instance

### ISSUE THREAD

**Issue by tomershvueli** [simonw/datasette#1190]
If I have a self-hosted instance of Datasette up and running, I'd like to be able to the use the CLI to publish databases to that instance, not only Google or Heroku. Ideally there'd be a `url` parameter or something similar to which one could point the publish command to their instance.

**Comment by simonw** [comment]
I really like this idea. It feels like an opportunity for a plugin that adds two things: an API endpoint to Datasette for accepting uploaded databases, and a `datasette publish upload` subcommand which can upload files to that endpoint (with some kind of authentication mechanism).

**Comment by simonw** [comment]
This ties in to a bunch of other ideas that are in flight at the moment.

If you're publishing databases by uploading them, how do you attach metadata? Ideally by baking it into the database file itself, using the mechanism from #1169.

How could this interact with the `datasette insert` concept from #1163? Could you pass a CSV file to the `upload` command and have that converted and uploaded for you, or would you create the database file locally using `datasette insert` and then upload it as a separate `datasette upload` step?

Lots to think about here.

**Comment by simonw** [comment]
This is going to happen in this tool instead:
- https://github.com/simonw/dclient
