### ISSUE TITLE
DB size limit for publishing with Heroku

### ISSUE THREAD

**Issue by mtdukes** [simonw/datasette#1197]
Hello,
I tried searching for this, but can't seem to get a great answer: Does anybody know the size limit for databases deploying to Heroku? The files I'm working with are pretty large, but I might be able to pare them down if I have a limit in mind.

 I'm getting the following error when running `datasette heroku publish`:

`RangeError [ERR_INVALID_OPT_VALUE]: The value "14504095744" is invalid for option "size"`

**Comment by simonw** [comment]
https://devcenter.heroku.com/articles/slug-compiler#slug-size says that the maximum allowed size is 500MB - my hunch is that the Datasette application itself weighs in at only a dozen or so MB but I haven't measured it. So I would imagine anything up to around 450MB should work OK on Heroku.

Cloud Run works for up to about 2GB in my experience.
