### ISSUE TITLE
Plugin that adds an authentication layer of some sort

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#120]
Would allow people who want to host private data to do so.
.sh

**Comment by nickdirienzo** [comment]
Ah, glad I found this issue. I have private data that I'd like to share to a few different people. Personally, a shared username and password would be sufficient for me, more-or-less Basic Auth. Do you have more complex requirements in mind?

I'm not sure if "plugin" means "build a plugin" or "find a plugin" or something else entirely. FWIW, I stumbled upon [sanic-auth](https://github.com/pyx/sanic-auth) which looks like a new project to bring some interfaces around auth to sanic, similar to Flask.

Alternatively, it shouldn't be too bad to add in Basic Auth. If we went down that route, that would probably be best built as a separate package for sanic that `datasette` brings in.

What are your thoughts around this?

**Comment by ad-si** [comment]
This would be an awesome feature ❤️

**Comment by duarteocarmo** [comment]
I would really like this. If you give me some pointers @simonw I'm willing to PR!

**Comment by simonw** [comment]
I've built two of these so far: https://github.com/simonw/datasette-auth-github and https://github.com/simonw/datasette-auth-existing-cookies

Closing this ticket in favour of #699
