### ISSUE TITLE
Immutable Database w/ Canned Queries

### ISSUE THREAD

**Issue by heyarne** [simonw/datasette#1210]
I have a database that I only want to read from; when instructing datasette to treat the database as immutable my defined canned queries disappear. Are these two features incompatible or have I hit an unintended bug? Thanks for datasette in any way, it's a joy to use!

**Comment by simonw** [comment]
That definitely sounds like a bug! Can you provide a copy of your `metadata.JSON` and the command-line you are using to launch Datasette?

**Comment by heyarne** [comment]
Thanks for your quick reply! Having changed my `metadata.yml`, queries AND database I can't really reproduce it anymore, sorry. But at least I'm happy to say that it works now! :) Thanks again for the super nifty tool, very appreciated.
