### ISSUE TITLE
Installing datasette via docker: Path 'fixtures.db' does not exist

### ISSUE THREAD

**Issue by aborruso** [simonw/datasette#1220]
Hi,
If I run

```
docker run -p 8001:8001 -v `pwd`:/mnt \                                                                         1 ↵
    datasetteproject/datasette \
    datasette -p 8001 -h 0.0.0.0 fixtures.db
```

I have 

```
Error: Invalid value for '[FILES]...': Path 'fixtures.db' does not exist.
```

If I run `test -f fixtures.db && echo "it exists."` I have `it exists.`.

What's my error?

Thank you

**Comment by bobwhitelock** [comment]
According to https://github.com/simonw/datasette/blob/master/docs/installation.rst#using-docker it should be

```
docker run -p 8001:8001 -v `pwd`:/mnt \
    datasetteproject/datasette \
    datasette -p 8001 -h 0.0.0.0 /mnt/fixtures.db
```

This uses `/mnt/fixtures.db` whereas you're using `fixtures.db` - did you try using this path instead?

**Comment by aborruso** [comment]
I have used my path, I'm running it from the folder in wich I have the db.

Do I must an absolute path?

Do I must create exactly that folder?

**Comment by bobwhitelock** [comment]
That Docker command will mount your current directory inside the Docker container at `/mnt` - so you shouldn't need to change anything locally, just run

```
docker run -p 8001:8001 -v `pwd`:/mnt \
    datasetteproject/datasette \
    datasette -p 8001 -h 0.0.0.0 /mnt/fixtures.db
```

and it will use the `fixtures.db` file within your current directory

**Comment by aborruso** [comment]
Thank you
