### ISSUE TITLE
Ability to increase size of the SQL editor window

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#1236]

**Comment by simonw** [comment]
I can use https://github.com/Sphinxxxx/cm-resize for this

**Comment by simonw** [comment]
I only want it to resize up and down, not left to right - so I'm not keen on the default resize handle:

<img width="722" alt="cm-resize_demo" src="https://user-images.githubusercontent.com/9599/108573363-364de680-72c9-11eb-8741-5112463ebfaa.png">

https://rawgit.com/Sphinxxxx/cm-resize/master/demo/index.html

**Comment by simonw** [comment]
I'm going to use a variant of the Datasette menu icon. Here it is in `#ccc` with an ARIA label:

```svg
<svg aria-labelledby="cm-drag-to-resize" role="img" fill="#ccc" stroke="#ccc" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="16" height="16">
  <title id="cm-drag-to-resize">Drag to resize</title>
  <path fill-rule="evenodd" d="M1 2.75A.75.75 0 011.75 2h12.5a.75.75 0 110 1.5H1.75A.75.75 0 011 2.75zm0 5A.75.75 0 011.75 7h12.5a.75.75 0 110 1.5H1.75A.75.75 0 011 7.75zM1.75 12a.75.75 0 100 1.5h12.5a.75.75 0 100-1.5H1.75z"></path>
</svg>
```

**Comment by simonw** [comment]
Encoded using https://meyerweb.com/eric/tools/dencoder/

`%3Csvg%20aria-labelledby%3D%22cm-drag-to-resize%22%20role%3D%22img%22%20fill%3D%22%23ccc%22%20stroke%3D%22%23ccc%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%2016%2016%22%20width%3D%2216%22%20height%3D%2216%22%3E%0A%20%20%3Ctitle%20id%3D%22cm-drag-to-resize%22%3EDrag%20to%20resize%3C%2Ftitle%3E%0A%20%20%3Cpath%20fill-rule%3D%22evenodd%22%20d%3D%22M1%202.75A.75.75%200%20011.75%202h12.5a.75.75%200%20110%201.5H1.75A.75.75%200%20011%202.75zm0%205A.75.75%200%20011.75%207h12.5a.75.75%200%20110%201.5H1.75A.75.75%200%20011%207.75zM1.75%2012a.75.75%200%20100%201.5h12.5a.75.75%200%20100-1.5H1.75z%22%3E%3C%2Fpath%3E%0A%3C%2Fsvg%3E`

**Comment by simonw** [comment]
![resize-demo](https://user-images.githubusercontent.com/9599/108573758-4914eb00-72ca-11eb-989c-e642eee68021.gif)

**Comment by simonw** [comment]
Now live on https://latest.datasette.io/_memory

**Comment by simonw** [comment]
Need to test this on mobile.

**Comment by simonw** [comment]
It's good on mobile - iOS at least. Going to close this open new issues if anyone reports bugs.

**Comment by mroswell** [comment]
That corner handle looks like a hamburger menu to me. Note that the default resize handle is not limited to two-way resize: http://jsfiddle.net/LLrh7Lte/
