### ISSUE TITLE
Option to open readonly but not immutable

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#124]
Immutable assumes no other process can modify the file. An option to open reqdonly instead would enable other processes to update the file in place.

**Comment by janimo** [comment]
Are there performance gains when using immutable as opposed to read-only? From what I see other processes can still modify the DB when immutable, but there are no change notifications.

**Comment by simonw** [comment]
https://sqlite.org/c3ref/open.html Is the only documentation I've been able to find of the immutable option:

> **immutable**: The immutable parameter is a boolean query parameter that indicates that the database file is stored on read-only media. When immutable is set, SQLite assumes that the database file cannot be changed, even by a process with higher privilege, and so the database is opened read-only and all locking and change detection is disabled. Caution: Setting the immutable property on a database file that does in fact change can result in incorrect query results and/or SQLITE_CORRUPT errors.

**Comment by janimo** [comment]
That's the only reference to immutable I saw as well, making me think that there may be no perceivable advantages over simply using mode=ro. Since the database is never or seldom updated the change notifications should not impact performance.

**Comment by simonw** [comment]
I'd really like to get some benchmarks working so I can see the actual impact of this kind of thing.

**Comment by simonw** [comment]
https://simonwillison.net/2019/May/19/datasette-0-28/
