### ISSUE TITLE
duckdb database (very low performance in SQLite)

### ISSUE THREAD

**Issue by verajosemanuel** [simonw/datasette#1248]
My sqlite is getting too big to be processed by datasette (more than 10 minutes waiting to load) so I am working with duckdb and is waaaaay faster. I think the fastest embeddable database actually.

https://duckdb.org/

Taking into account DuckDb is SQLite based it would be GREAT to use it with datasette.

is that possible?

Regards and thanks for a superb job

**Comment by simonw** [comment]
It's not possible yet, unfortunately. This came up on the forums recently: https://github.com/simonw/datasette/discussions/968

I'm leaning further towards making the database connection layer itself work via a plugin hook, which would open up the possibility of supporting DuckDB and other databases as well. I've not committed to doing this yet though.
