### ISSUE TITLE
Plot rows on a map with Leaflet and Leaflet.markercluster

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#125]
https://github.com/Leaflet/Leaflet.markercluster would allow us to paginate-load in an enormous set of rows with latitude/longitude points, e.g. https://australian-dunnies.now.sh/

Here's a demo of it loading 50,000 markers: https://leaflet.github.io/Leaflet.markercluster/example/marker-clustering-realworld.50000.html - and it looks like it's easy to support progress bars for if we were iteratively loading 1,000 markers at a time using datasette pagination.

**Comment by russss** [comment]
FWIW I am now doing this on my WTR app (instead of silently limiting maps to 1000).

[Telefonica](https://wtr-api.herokuapp.com/wtr-663ea99/licensee/18325) now has about 4000 markers and good old [BT](https://wtr-api.herokuapp.com/wtr-663ea99/licensee/8412) has 22,000 or so.

**Comment by simonw** [comment]
I shipped this last week as the first plugin: https://simonwillison.net/2018/Apr/20/datasette-plugins/

Demo: https://datasette-cluster-map-demo.datasettes.com/polar-bears-455fe3a/USGS_WC_eartags_output_files_2009-2011-Status

Plugin: https://github.com/simonw/datasette-cluster-map
