### ISSUE TITLE
Some links aren't properly URL encoded.

### ISSUE THREAD

**Issue by brimstone** [simonw/datasette#1261]
It seems like a percent sign in the query causes some links to end invalid.

The json and CSV links on this page don't behave like expected: https://honeypot-brimston3.vercel.app/honeypot?sql=select+time%2C+count%28time%29+as+count+from+%28select+strftime%28%22%25Y-%25m-%25d%22%2C+_etime%29+as+time+from+ssh+%29+group+by+time+order+by+time%3B

I can take a swing at trying to fix this, but my python isn't strong and I need a pointer at the right approach and files to change.

Thanks!

**Comment by simonw** [comment]
This isn't a Datasette bug - it's a Vercel bug: https://github.com/simonw/datasette-publish-vercel/issues/28

I'm looking at a fix for that now, so watch that issue for updates.

**Comment by simonw** [comment]
That's fixed in this release of `datasette-publish-vercel`: https://github.com/simonw/datasette-publish-vercel/releases/tag/0.9.2

**Comment by brimstone** [comment]
I can confirm 0.9.2 fixes the problem. Thanks for the fast response!
