### ISSUE TITLE
Support for HTTP Basic Authentication

### ISSUE THREAD

**Issue by yunzheng** [simonw/datasette#1265]
It would be nice if datasette could support [HTTP Basic Authentication](https://en.wikipedia.org/wiki/Basic_access_authentication).

For now I could ofcourse leverage Nginx for basic authentication, but it would be nice to have support for this in datasette by default or via a plugin like datasette-auth-github.

My main usecase is to put the whole datasette instance behind a username/password prompt via Basic Auth and not specific urls.

**Comment by bobwhitelock** [comment]
It doesn't use basic auth, but you can put a whole datasette instance, or parts of this, behind a username/password prompt using https://github.com/simonw/datasette-auth-passwords

**Comment by simonw** [comment]
This is now available in `datasette-auth-passwords` 0.4! https://github.com/simonw/datasette-auth-passwords/releases/tag/0.4

**Comment by yunzheng** [comment]
Wow that was fast! Thanks for this very cool project and quick update! 👍
