### ISSUE TITLE
Update Datasette alternativeto listening with details

### ISSUE THREAD

**Issue by RayBB** [simonw/datasette#1267]
Hello,

I recently learned about Datasette from an old hackernews post. It seems like an awesome project and I actually have use case I might be trying out in the coming months.

Alas, to get a better understanding of your project I looked it up on alternativeto to see what it is similar too. I promise it's not spam, it's reputable enough to have a [Wikipedia](https://en.wikipedia.org/wiki/AlternativeTo) page. There was no listing on the website so I went ahead and created a listing that is now approved.

I encourage anyone who likes this project and hopes to spread the word to help update the listing by:
1. Adding to the list of software it compares to
2. Uploading screenshots
3. Writing a review
4. Adding "features"

I know this may seem spammy but I promise I have no affiliation with alternativeto I'm just a happy user and know it's a popular site for discovering software.

Here is the listing for datasette:
https://alternativeto.net/software/datasette/about/

Cheers

**Comment by simonw** [comment]
Thanks for doing this - I've used alternativeto.net a bunch in the past, it's great to see Datasette listed there.

This does raise some interesting philosophical questions: three years into the project I'm still not entirely sure what Datasette competes with! Could be SQLite desktop packages, could be visualization software like Tableau, could even be something like Airtable (given a few more plugins).

It will be interesting to see how the alternativeto listing evolves, maybe it will help me answer that question!
