### ISSUE TITLE
Support Unicode characters in metadata.json

### ISSUE THREAD

**Issue by GmGniap** [simonw/datasette#1327]
Hello , when I used Burmese (Unicode) characters in metadata.json like below - 
![image](https://user-images.githubusercontent.com/20846286/118364978-cba70100-b5c0-11eb-967c-7dc3b62478f2.png)

It gave wrong results when I run datasette - 
![image](https://user-images.githubusercontent.com/20846286/118365025-fc873600-b5c0-11eb-97ce-19541b8cc6d8.png)

It would be great & helpful for us if metadata.json can support in Unicode supported Asian Languages. 
Thanks & Regards.

**Comment by simonw** [comment]
I'm having trouble replicating this - I tried the following `metadata.json` in my local environment and it displayed correctly:
```json
{
    "title": "မြန်မာစာ ("
}
```
What operating system are you using here? Is there a chance that your `metadata.json` file is saved in a text encoding other than utf-8?

**Comment by GmGniap** [comment]
wow, thanks a lot @simonw , problem is solved. I converted my current json file into utf-8 format with Python script. It's working now. I'm using with Window 10.
