### ISSUE TITLE
Add support for Jinja2 version 3.0

### ISSUE THREAD

**Issue by MarkusH** [simonw/datasette#1331]
A week ago, [The Pallets Project](https://github.com/pallets) released [new major versions of several of its projects](https://palletsprojects.com/blog/flask-2-0-released/). Among those updates is one for Jinja2, which bumps it to version 3.0.0.

I'd like for datasette to support Jinaj2 version 3.0.

**Comment by simonw** [comment]
Datasette uses async templates which evidently have been improved in Jinja 3.

**Comment by simonw** [comment]
The tests are passing on #1324 so this may not require any code changes at all!

**Comment by MarkusH** [comment]
Wow, you are _fast_!

I didn't notice dependabot had opened a PR already. I was about to.

**Comment by simonw** [comment]
I wonder if there are any new 3.0 features we should be taking advantage of here that would justify pinning to 3.0 minimum?

**Comment by MarkusH** [comment]
> I wonder if there are any new 3.0 features we should be taking advantage of here that would justify pinning to 3.0 minimum?

The changelog reads like bug fixes and removal of deprecated parts to me

**Comment by MarkusH** [comment]
Any chance you could push a new datasette release with the updated dependencies in the setup.py, @simonw?

**Comment by stonebig** [comment]
I'm stuck also because  datasette wants itsdangerous~=1.1 instead of allowing itsdangerous-2.0.0

**Comment by simonw** [comment]
I'm going to push an alpha release with the new dependencies shortly.

**Comment by simonw** [comment]
> I'm stuck also because datasette wants itsdangerous~=1.1 instead of allowing itsdangerous-2.0.0

Bumped that dependency in b64d87204612a84663616e075f542499a5d82a03

**Comment by simonw** [comment]
Here's an alpha release with updated dependencies: https://pypi.org/project/datasette/0.57a0/
