### ISSUE TITLE
?_facet_size=X to increase number of facets results on the page

### ISSUE THREAD

**Issue by mroswell** [simonw/datasette#1332]
Is there a way to add a parameter to the URL to modify default_facet_size?

LIkewise, a way to produce a link on the three dots to expand to all items (or match previous number of items, or add x more)?

**Comment by simonw** [comment]
A URL parameter to modify that facet size is a really good idea.

I thought I had an issue open for "..." linking to more results but I can't find it now.

**Comment by simonw** [comment]
`?_facet_size=50` seems like a very reasonable thing to support - I'll cap it at whatever the `max_returned_rows` setting is (which defaults to 1000).

**Comment by simonw** [comment]
Here's the code in question: https://github.com/simonw/datasette/blob/5e9672c9bb33e41686472db4aa427168f9e67dbe/datasette/facets.py#L187-L210

It has access to the current request object as `self.request`.

**Comment by simonw** [comment]
Documentation:

- https://docs.datasette.io/en/latest/facets.html#facets-in-query-strings at the bottom of the section
- https://docs.datasette.io/en/latest/json_api.html#special-table-arguments at the bottom of the list of arguments

**Comment by simonw** [comment]
Added `?_facet_size=max` in #1337 and made the `...` truncated note link to that - here's a demo: https://fivethirtyeight.datasettes.com/fivethirtyeight/antiquities-act%2Factions_under_antiquities_act?_facet=states&_facet=current_agency&_facet=pres_or_congress
