### ISSUE TITLE
Datasette with Glitch - is it possible to use CSV with ISO-8859-1 encoding?

### ISSUE THREAD

**Issue by reichaves** [simonw/datasette#1382]
Hi
Please, I used Remix on Glitch to create a project on Glitch and uploaded a CSV
But it's a CSV with ISO-8859-1 encoding (https://en.wikipedia.org/wiki/ISO/IEC_8859-1)
Is it possible for me to change the encoding to correctly visualize the data?
Example: https://emphasized-carpal-pillow.glitch.me/data/Emendas
Best

**Comment by simonw** [comment]
Yes you can - thanks for pointing this out, I've added a comment to the `build.sh` script in the `datasette-csvs` Glitch project:

```bash
pip3 install -U --no-cache-dir -r requirements.txt --user && \
  mkdir -p .data && \
  rm .data/data.db || true && \
  for f in *.csv
    do
      # Add --encoding=latin-1 to the following if your CSVs use a different encoding:
      sqlite-utils insert .data/data.db ${f%.*} $f --csv
    done
```

So if you edit that file in your own project and change the line to this:

      sqlite-utils insert .data/data.db ${f%.*} $f --csv --encoding=iso-8859-1

It should fix this for you.
