### ISSUE TITLE
Serve using UNIX domain socket

### ISSUE THREAD

**Issue by aslakr** [simonw/datasette#1388]
Would it be possible to make datasette serve using UNIX domain socket similar to Uvicorn's ``--uds``?

**Comment by simonw** [comment]
This sounds like a valuable feature for people running Datasette behind a proxy.

**Comment by simonw** [comment]
Looks pretty easy to implement - here's a hint from Uvicorn source code: https://github.com/encode/uvicorn/blob/b5af1049e63c059dc750a450c807b9768f91e906/uvicorn/main.py#L368

Need to work out a simple pattern for testing this too.

**Comment by simonw** [comment]
You could actually run Datasette like this today without modifications by running a thin Python script that imports from `datasette.app`, instantiates the ASGI app and passes that to `uvicorn.run` - but I like this as a supported feature too.

**Comment by simonw** [comment]
I wonder if `--fd` is worth supporting too? Uvicorn documentation says that's useful for running under process managers, I'd want to understand exactly how to use that (and test it) before adding the feature though.

**Comment by aslakr** [comment]
> This sounds like a valuable feature for people running Datasette behind a proxy.

Yes, in some cases it is easer to use e.g. Apache's [ProxyPass Directive](https://httpd.apache.org/docs/2.4/mod/mod_proxy.html#proxypass) with Unix Domain Socket like  `unix:/home/www.socket|http://localhost/whatever/`.

**Comment by simonw** [comment]
Can test this with:
```
curl --unix-socket ${socket} -i "http://localhost/" 
```

**Comment by simonw** [comment]
I can run tests against it using `httpx`: https://www.python-httpx.org/advanced/#usage_1

> ```pycon
> >>> import httpx
> >>> # Connect to the Docker API via a Unix Socket.
> >>> transport = httpx.HTTPTransport(uds="/var/run/docker.sock")
> >>> client = httpx.Client(transport=transport)
> >>> response = client.get("http://docker/info")
> ```

**Comment by simonw** [comment]
I don't have the Datasette test suite running on Windows yet, but I'd like it to run there some day - so ideally this test would be skipped if Unix domain sockets are not supported by the underlying operating system.

**Comment by simonw** [comment]
Apparently Windows 10 has Unix domain socket support: https://bugs.python.org/issue33408

> Unix socket (AF_UNIX) is now avalible in Windows 10 (April 2018 Update). Please add Python support for it.
> More details about it on https://blogs.msdn.microsoft.com/commandline/2017/12/19/af_unix-comes-to-windows/

But it's not clear if this is going to work. That same issue thread (the issue is still open) suggests using `hasattr(socket, 'AF_UNIX'))` to detect support in tests.

**Comment by simonw** [comment]
Figured out an example nginx configuration. This in `nginx.conf`:

    daemon off;
    events {
      worker_connections  1024;
    }
    http {
      server {
        listen 8092;
        location / {
          proxy_pass              http://datasette;
          proxy_set_header        X-Real-IP $remote_addr;
          proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        }
      }
      upstream datasette {
        server unix:/tmp/datasette.sock;
      }
    }

Then run `datasette --uds /tmp/datasette.sock`

Then run nginx like this:

    nginx -c ./nginx.conf

Then hits to `http://localhost:8092/` will be proxied to Datasette.

**Comment by simonw** [comment]
> I wonder if `--fd` is worth supporting too?

I'm going to hold off on implementing this until someone asks for it.

**Comment by simonw** [comment]
Documentation: https://docs.datasette.io/en/latest/deploying.html#nginx-proxy-configuration

**Comment by simonw** [comment]
Wrote up a TIL: https://til.simonwillison.net/nginx/proxy-domain-sockets
