### ISSUE TITLE
datasette publish can fail if /tmp is on a different device

### ISSUE THREAD

**Issue by jacobian** [simonw/datasette#141]
`datasette publish` uses hard links to avoid copying the db into a tmp directory. This can fail if `/tmp` is on another device, because hardlinks can't cross devices. You'll see something like this:

```
$ datasette publish heroku whatever.db
...
OSError: [Errno 18] Invalid cross-device link: '/mnt/c/Users/jacob/c/datasette/whatever.db' -> '/tmp/tmpvxq2yof6/whatever.db'
```
[In my case this is failing because I'm on a Windows machine, using WSL, so my code's on a different virtual filesystem from the Linux subsystem, Because Reasons.]

I'm not sure if it's possible to detect this (can you figure out which device `/tmp` is on?), or what the fallback should be (soft link? copy?).

**Comment by simonw** [comment]
I think a copy is the right thing to do here - it will be cleaned up when the temp directory is removed. The hard link thing was always intended to save space, but if we can't do a hard link I don't see any harm in a temporary file copy.

**Comment by janimo** [comment]
FWIW I worked around this by setting TMPDIR to ~/tmp before running the command.

**Comment by simonw** [comment]
I can emulate this on OS X using a disk image (Disk Utility -> File -> New Image -> Blank Image...) - once mounted, I get the following:

    >>> os.link('/tmp/hello', '/Volumes/Untitled/hello')
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    OSError: [Errno 18] Cross-device link: '/tmp/hello' -> '/Volumes/Untitled/hello'

I can simulate that in a mock like this:

	>>> from unittest.mock import patch
	>>> @patch('os.link')
	... def test_link(mock_link):
	...     mock_link.side_effect = OSError
	...     mock_link()
	...

**Comment by simonw** [comment]
This fix should work, please have a go with latest master and let me know if you run into any problems.

**Comment by simonw** [comment]
This bug raised its head again in #744,
