### ISSUE TITLE
Show count of facet values if ?_facet_size=max

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#1423]
I sometimes want to get a count of the values in a facet - if it's a facet of US states for example I want to know if all 50 are represented.

Idea: if `?_facet_size=max` is present, add a count to the facet heading. So on:

https://latest.datasette.io/fixtures/compound_three_primary_keys?_facet=content&_facet_size=max&_facet=pk1&_facet=pk2#facet-pk2

It could have something like this:

<img width="658" alt="fixtures__compound_three_primary_keys__1_001_rows_and_NY_629_755_•_Untitled-1_—_datasette" src="https://user-images.githubusercontent.com/9599/128456981-1f3d5348-90f1-45cc-9287-0f7bb0015257.png">

Note that the first column shows >1000 - because in that case we've truncated the facet calculation since the maximum allowed returned rows is 1000.

**Comment by simonw** [comment]
Problem: on a page which doesn't have quite enough facet values to trigger the display of the "..." link that links to `?_facet_size=max` the user would still have to manually count the values - up to 30 by default.

So maybe the count should always be shown?

**Comment by simonw** [comment]
Could display them always, like this:

<img width="1299" alt="fixtures__compound_three_primary_keys__1_001_rows_and_School_enrollment_analysis_Colorado_-_Google_Docs" src="https://user-images.githubusercontent.com/9599/128557997-6bedb52b-45f1-4ab1-9a79-ddf6c01f6036.png">

That's with `<span style="font-size: 0.8em;color: #666;">23</span>`

**Comment by simonw** [comment]
Point of confusion: if only 30 options are shown, but there's a `...` at the end, what would the number be? It can't be the total number of facets because we haven't counted them all - but if it's just the number of displayed facets that's like to be confusing.

So the original idea of showing the counts only if `_facet_size=max` is a good one.

**Comment by simonw** [comment]
The invisible tooltip could say "Showing 30 items, more available" (helping save you from counting up to 20 if you know about the secret feature). The numbers could then be fully displayed on the "..." page.

**Comment by simonw** [comment]
This means that the counts would be unavailable to users who cannot see tooltips (e.g. mobile users) on pages that did not have any facets that broke the 30 limit and hence displayed that "..." link.

I think I'm OK with that, for the moment. May revisit in the future.

**Comment by simonw** [comment]
I didn't bother with the tooltip, just the visible display if `?_facet_size=max`.

**Comment by simonw** [comment]
Demo: https://latest.datasette.io/fixtures/compound_three_primary_keys?_facet=content&_facet_size=max&_facet=pk1&_facet=pk2

<img width="686" alt="fixtures__compound_three_primary_keys__1_001_rows" src="https://user-images.githubusercontent.com/9599/129616596-cc51b668-7cb8-482f-9e20-e0d8ca4b71be.png">

**Comment by pavopax** [comment]
Great feature.

But what is the right way to enable this to show up? Currently, it seems I need to edit the URL to add, in the right place, `&_facet_size=max`

Is there another (easier) way to enable this feature?

**Comment by simonw** [comment]
You've caused me to rethink this feature - I no longer think there's value in only showing these numbers if `?_facet_size=max` as opposed to all of the time. New issue coming up.
