### ISSUE TITLE
render_cell() hook should support returning an awaitable

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#1425]
Many of the plugin hooks can return an awaitable - e.g. https://docs.datasette.io/en/stable/plugin_hooks.html#plugin-hook-extra-template-vars - but `render_cell()` doesn't support this.

I recently found myself wanting to execute an additional SQL query from that hook, but it wasn't possible to do that since I couldn't use `await`.

**Comment by simonw** [comment]
I can do this with the `await_me_maybe()` function, as seen here: https://github.com/simonw/datasette/blob/a21853c9dade240734abc6b4f750fae09a3e840a/datasette/app.py#L864-L873

**Comment by simonw** [comment]
Updated documentation: https://docs.datasette.io/en/latest/plugin_hooks.html#render-cell-value-column-table-database-datasette

**Comment by simonw** [comment]
Still one test failure:
```
    def test_hook_render_cell_link_from_json(app_client):
        sql = """
            select '{"href": "http://example.com/", "label":"Example"}'
        """.strip()
        path = "/fixtures?" + urllib.parse.urlencode({"sql": sql})
        response = app_client.get(path)
        td = Soup(response.body, "html.parser").find("table").find("tbody").find("td")
        a = td.find("a")
>       assert a is not None, str(a)
E       AssertionError: None
E       assert None is not None
```
The weird thing about this one is that I can't replicate it on my laptop - but it happens in CI every time, including when I shell in and try to run that single test.

**Comment by simonw** [comment]
My hunch is that the "skip this `render_cell()` result if it returns `None`" logic isn't working correctly, since when I added the `await_me_maybe` line.

Could that be because Pluggy handles the "do the next if `None` is returned" logic itself, but I'm no-longer returning `None`, I'm returning an awaitable which when awaited returns `None`.

This would suggest that all of the `await_me_maybe()` plugin hooks have the same bug. That's definitely possible - it may well be that no-one has yet stumbled across a bug caused by a plugin returning an awaitable and hence not being skipped, because plugin hooks that return awaitable are rare enough that no-one has tried two plugins which both use that trick.

Still don't see why it would pass on my laptop but fail in CI though.

**Comment by simonw** [comment]
Good news: `render_cell()` is the only hook to use `firstresult=True`:

https://github.com/simonw/datasette/blob/f3c9edb376a13c09b5ecf97c7390f4e49efaadf2/datasette/hookspecs.py#L62-L64

https://pluggy.readthedocs.io/en/latest/#first-result-only

**Comment by simonw** [comment]
Here's the code in `pluggy` that implements this: https://github.com/pytest-dev/pluggy/blob/0a064fe275060dbdb1fe6e10c888e72bc400fb33/src/pluggy/callers.py#L31-L43

```python
                if hook_impl.hookwrapper:
                    try:
                        gen = hook_impl.function(*args)
                        next(gen)  # first yield
                        teardowns.append(gen)
                    except StopIteration:
                        _raise_wrapfail(gen, "did not yield")
                else:
                    res = hook_impl.function(*args)
                    if res is not None:
                        results.append(res)
                        if firstresult:  # halt further impl calls
                            break
```

**Comment by simonw** [comment]
I could extract that code out and write my own function which implements the equivalent of calling `pm.hook.render_cell(...)` but runs `await_me_maybe()` before checking if `res is not None`.

That's pretty nasty.

Could I instead call the plugin hook normally, but then have additional logic which says "if I await it and it returns `None` then try calling the hook again but skip this one" - not sure if there's a way to do that either.

I could remove the `firstresult=True` from the hookspec - which would cause it to call and return ALL hooks - but then in my own code use only the first one. This is slightly less efficient (since it calls all the hooks and then discards all-but-one value) but it's the least unpleasant in terms of the code I would have to write - plus I don't think it's going to be THAT common for someone to have multiple expensive `render_cell()` hooks installed at once (they are usually pretty cheap).

**Comment by simonw** [comment]
I'm trying the version where I remove `firstresult=True`.

**Comment by simonw** [comment]
Demo: https://latest.datasette.io/fixtures/simple_primary_key shows `RENDER_CELL_ASYNC_RESULT` where the CSV version shows `RENDER_CELL_ASYNC`: https://latest.datasette.io/fixtures/simple_primary_key.csv - because of this test plugin code: https://github.com/simonw/datasette/issues/1425

**Comment by simonw** [comment]
I used this to build a new plugin: https://github.com/simonw/datasette-query-links

Demo here: https://latest-with-plugins.datasette.io/fixtures?sql=select%0D%0A++%27select+*+from+[facetable]%27+as+query%0D%0Aunion%0D%0Aselect%0D%0A++%27select+sqlite_version()%27%0D%0Aunion%0D%0Aselect%0D%0A++%27select+this+is+invalid+SQL+so+will+not+be+linked%27

**Comment by abdusco** [comment]
I believe this also provides a workaround for the problem I face in https://github.com/simonw/datasette/issues/1300. 

Now I should be able to get table PKs and generate a row URL. I'll test this out and report my findings.


```py
from datasette.utils import path_from_row_pks

pks = await db.primary_keys(table)
url = self.ds.urls.row_blob(
    database,
    table,
    path_from_row_pks(row, pks, not pks),
    column,
)
```
