### ISSUE TITLE
Rename Datasette.__init__(config=) parameter to settings=

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#1432]
> While I'm doing this I should rename this internal variable to avoid confusion in the future:
>
> https://github.com/simonw/datasette/blob/e837095ef35ae155b4c78cc9a8b7133a48c94f03/datasette/app.py#L203

_Originally posted by @simonw in https://github.com/simonw/datasette/issues/1431#issuecomment-898072940_

**Comment by simonw** [comment]
Also this method: https://github.com/simonw/datasette/blob/77f46297a88ac7e49dad2139410b01ee56d5f99c/datasette/app.py#L422-L424

And the places that use it:

https://github.com/simonw/datasette/blob/fc4846850fffd54561bc125332dfe97bb41ff42e/datasette/views/base.py#L617

https://github.com/simonw/datasette/blob/fc4846850fffd54561bc125332dfe97bb41ff42e/datasette/views/database.py#L459

Which is used in this template: https://github.com/simonw/datasette/blob/77f46297a88ac7e49dad2139410b01ee56d5f99c/datasette/templates/table.html#L204

**Comment by simonw** [comment]
This is going to break some plugins: https://ripgrep.datasette.io/-/ripgrep?pattern=config%3D&literal=on&glob=%21datasette%2F**

I should fix those as soon as this goes out in a release. I won't close this issue until then.

**Comment by simonw** [comment]
It's only `datasette-publish-vercel` that will break the actual functionality - the others will have broken tests.

**Comment by ashishdotme** [comment]
@simonw I am getting the below issue again now, even after removing branch argument from vercel datasette plugin

module initialization error: init() got an unexpected keyword argument 'config'
module initialization error
init() got an unexpected keyword argument 'config'

**Comment by mroswell** [comment]
Resolved, with assistance from @ashishdotme (Thank you!)

Updated requirements.txt to include:
```
datasette==0.59
datasette-publish-vercel==0.11
sqlite-utils==3.6
```

Ran:
```
$ pip3 install -r requirements.txt
```
The site is back at work! Yay!

**Comment by simonw** [comment]
This issue is obsolete thanks to the new metadata v.s. config change in Datasette 1.0.
