### ISSUE TITLE
?_sort=rowid with _next= returns error

### ISSUE THREAD

**Issue by eigenfoo** [simonw/datasette#1470]
For example:

- Go to https://cryptics.eigenfoo.xyz/clues/clues?_next=100 (this is the second page of results in a Datasette site)
- Search anything using the FTS search bar. For example, searching for `hello` will take you to https://cryptics.eigenfoo.xyz/clues/clues?_search=hello&_sort=rowid&_next=100
- A `500 Error: list index out of range` is raised.

This is because the search URL includes the `&_next=100` UTM parameter, carried over from where the FTS search was run. However, there isn't a second page in the search results, so a `list index out of range` error is raised. You can confirm that removing this UTM parameter from the URL returns the appropriate search results.

The FTS search request should strip any `_next` UTM parameter.

---

```bash
datasette, version 0.58.1
sqlite-utils, version 3.17
```

**Comment by simonw** [comment]
I'll open a separate issue for removing `_next=` when running a search.
