### ISSUE TITLE
validating the sql

### ISSUE THREAD

**Issue by Slender1808** [simonw/datasette#1546]
Could someone tell me that part of the code is responsible for validating the sql that guarantees that only a table can be read

**Comment by simonw** [comment]
Sure - there are actually several levels to this.

The code that creates connections to the database is this: https://github.com/simonw/datasette/blob/83bacfa9452babe7bd66e3579e23af988d00f6ac/datasette/database.py#L72-L95

For files on disk, it does this:
```python
# For read-only connections
conn = sqlite3.connect( "file:my.db?mode=ro", uri=True, check_same_thread=False)
# For connections that should be treated as immutable:
conn = sqlite3.connect( "file:my.db?immutable=1", uri=True, check_same_thread=False)
```
For in-memory databases it runs this after the connection has been created:
```python
conn.execute("PRAGMA query_only=1")
```
SQLite `PRAGMA` queries are treated as dangerous: someone could run `PRAGMA query_only=0` to turn that previous option off for example.

So this function runs against any incoming SQL to verify that it looks like a `SELECT ...` and doesn't have anything like that in it.

https://github.com/simonw/datasette/blob/83bacfa9452babe7bd66e3579e23af988d00f6ac/datasette/utils/__init__.py#L195-L204

You can see the tests for that here: https://github.com/simonw/datasette/blob/b1fed48a95516ae84c0f020582303ab50ab817e2/tests/test_utils.py#L136-L170
