### ISSUE TITLE
A primary key column that has foreign key restriction associated won't rendering label column

### ISSUE THREAD

**Issue by wsxiaoys** [simonw/datasette#155]

**Comment by simonw** [comment]
Could you provide the SQL to create a reproducible test case (both CREATE TABLE and INSERT statements)?

**Comment by wsxiaoys** [comment]
```
CREATE TABLE rhs (
  id INTEGER PRIMARY KEY,
  name TEXT
);

CREATE TABLE lhs (
  symbol INTEGER PRIMARY KEY,
  FOREIGN KEY (symbol) REFERENCES rhs(id)
);

INSERT INTO rhs VALUES (1, "foo");
INSERT INTO rhs VALUES (2, "bar");
INSERT INTO lhs VALUES (1);
INSERT INTO lhs VALUES (2);
```

It's expected that in lhs's view, foo / bar should be displayed.

**Comment by simonw** [comment]
Thanks!

**Comment by simonw** [comment]
Interestingly, it almost does the right thing on the individual row page: https://bug-155-dkcqckhgki.now.sh/bug-155-9a7bb68/lhs/1

<img width="303" alt="cursor_and_bug-155__lhs" src="https://user-images.githubusercontent.com/9599/33352129-511419e4-d45c-11e7-98f3-9c1dfefa6350.png">

The symbol has been expanded, but there's a rogue '1' that shouldn't be there at all - I think that's bug #152

The table view itself is definitely doing the wrong thing: https://bug-155-dkcqckhgki.now.sh/bug-155-9a7bb68/lhs

<img width="546" alt="cursor_and_bug-155__lhs__2_rows_and_paradise_papers_tie_kushner_startup_to_russian_money_ _the_forward" src="https://user-images.githubusercontent.com/9599/33352178-8491b9a2-d45c-11e7-8d89-fedd455cfcba.png">
