### ISSUE TITLE
Teach "datasette publish" about custom template directories

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#157]
The following command should copy the custom templates into the deployment and ensure `datasette serve` correctly serves them:

    datasette publish now mydb.db --template-dir=custom-templates/

**Comment by simonw** [comment]
Example usage:

    datasette package --static css:extra-css/ --static js:extra-js/ \
    	sf-trees.db --template-dir templates/ --tag sf-trees --branch master

This creates a local Docker image that includes copies of the templates/,
extra-css/ and extra-js/ directories. You can then run it like this:

	docker run -p 8001:8001 sf-trees

For publishing to Zeit now:

	datasette publish now --static css:extra-css/ --static js:extra-js/ \
		sf-trees.db --template-dir templates/ --name sf-trees --branch master

Example: https://sf-trees-wbihszoazc.now.sh/sf-trees-02c8ef1/Street_Tree_List

For publishing to Heroku:

	datasette publish heroku --static css:extra-css/ --static js:extra-js/ \
		sf-trees.db --template-dir templates/ --branch master

**Comment by null92** [comment]
Didn't work here. How I use the app.css on static folder as style sheet?
