### ISSUE TITLE
Ability to bundle and serve additional static files

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#160]
Since we now have custom templates, we should support including custom static files with them as well. Maybe something like this:

    datasette mydb.db --template-dir=templates/ --static-dir=static/

This should also be supported by datasette publish - see also #157

**Comment by simonw** [comment]
Question is... what should happen to the default static stuff? At the moment that's just https://fivethirtyeight.datasettes.com/-/static/app.css - though I want to improve that to include a content hash, see #154

**Comment by simonw** [comment]
This is about more than just CSS and JavaScript - there are plenty of reasons someone might want to bundle HTML as well, e.g. for building something like https://sf-tree-search.now.sh/

So, instead of thinking about this in terms of /static/, I'm going to think about this in terms of allowing people to mount one or more document roots (or docroots).

    datasette serve mydb.db -d my-doc-root/

This will cause the root of the server to show content from the `my-doc-root/` directory (assuming it has an index.html file in it).

A more common option will be to mount specific folders to specific directories, like this:

    datasette serve mydb.db -d static:my-static/

Now any hits to `/static/foo.css` will serve content from `my-static/foo.css`

**Comment by simonw** [comment]
Not sure which I like better out of `-d/--docroot` or `-s/--static` or `-m/--mount` for this.

**Comment by simonw** [comment]
`-m` is already taken for `--metadata`.

**Comment by simonw** [comment]
You can now tell Datasette to serve static files from a specific location at a
specific mountpoint.

For example:

	datasette serve mydb.db --static extra-css:/tmp/static/css

Now if you visit this URL:

	http://localhost:8001/extra-css/blah.css

The following file will be served:

	/tmp/static/css/blah.css

**Comment by simonw** [comment]
Still TODO: teach `datasette publish` and friends about this.

**Comment by simonw** [comment]
Example usage:

    datasette package --static css:extra-css/ --static js:extra-js/ \
    	sf-trees.db --template-dir templates/ --tag sf-trees --branch master

This creates a local Docker image that includes copies of the templates/,
extra-css/ and extra-js/ directories. You can then run it like this:

	docker run -p 8001:8001 sf-trees

For publishing to Zeit now:

	datasette publish now --static css:extra-css/ --static js:extra-js/ \
		sf-trees.db --template-dir templates/ --name sf-trees --branch master

Example: https://sf-trees-wbihszoazc.now.sh/sf-trees-02c8ef1/Street_Tree_List

For publishing to Heroku:

	datasette publish heroku --static css:extra-css/ --static js:extra-js/ \
		sf-trees.db --template-dir templates/ --branch master

**Comment by psychemedia** [comment]
Do you have any simple working examples of how to use `--static`? Inspection of default served files suggests locations such as `http://example.com/-/static/app.css?0e06ee`.

If `datasette` is being proxied to `http://example.com/foo/datasette`, what form should arguments to  `--static` take so that static files are correctly referenced?
