### ISSUE TITLE
Add KNN and data_licenses to hidden tables list

### ISSUE THREAD

**Issue by eyeseast** [simonw/datasette#1601]
They're generated by Spatialite and not very interesting in most cases.

<img width="626" alt="Screen Shot 2022-01-17 at 9 17 31 AM" src="https://user-images.githubusercontent.com/25778/149786443-7832363c-2a2c-4533-9edc-048cd00e4a08.png">

**Comment by simonw** [comment]
Good idea - though I'm nervous about accidentally hiding a `data_licenses` table outside of the SpatiaLite case. I'll only hide that one if SpatiaLite is loaded.

**Comment by simonw** [comment]
I need to add `sqlite_stat1` to the hidden tables too, see:
- https://github.com/simonw/sqlite-utils

**Comment by eyeseast** [comment]
I think both of these are Spatialite specific. They get generated when you first initialize the extension. KNN is actually deprecated in favor of [KNN2](https://www.gaia-gis.it/fossil/libspatialite/wiki?name=KNN2), as I understand it.

**Comment by simonw** [comment]
Oh interesting, I hadn't heard about KNN2. It looks like it was added to SpatiaLite on 21st June 2011 in https://www.gaia-gis.it/fossil/libspatialite/info/03786a62cdb4ab17 but the most recent release of SpatiaLite is 5.0.1 from 7th February 2021 - so it's not yet in a release.

**Comment by simonw** [comment]
I don't have solid tests in place for exercising SpatiaLite, but this change feels safe enough that I'm not going to add tests for it.
