### ISSUE TITLE
Documentation should clarify /stable/ vs /latest/

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#1608]
It's not currently clear what the difference between https://docs.datasette.io/en/latest/ and https://docs.datasette.io/en/stable/ is - I should fix that.

On Twitter: https://twitter.com/simonw/status/1484285006243528705

**Comment by simonw** [comment]
I think I want a banner at the top of the page making it obvious which version the documentation is talking about. This can be pretty low key for the current stable release, but should be visually more prominent for the `/latest/` branch and for older releases.

**Comment by simonw** [comment]
Might want to consider SEO here too - I want people from search engines to land on `/stable/`, I wonder if I should noindex or `rel=canonical` the other documentation versions? Not sure what best practices for that is.

**Comment by simonw** [comment]
Huh, I had forgotten I already have a banner on older versions:

![D1A65C68-9A37-4FA2-80C4-534739A9D292](https://user-images.githubusercontent.com/9599/150430410-1e22e23f-ed27-4271-89ff-63467eb5f466.jpeg)

**Comment by simonw** [comment]
Turns out that banner is something that ReadTheDocs implemented - I found it using GitHub code search, it's produced by this piece of JavaScript: https://github.com/readthedocs/readthedocs.org/blob/0852d7c10d725d954d3e9a93513171baa1116d9f/readthedocs/core/static-src/core/js/doc-embed/version-compare.js#L13-L21

**Comment by simonw** [comment]
I'm tempted to imitate their JavaScript but check for `/latest/` in the URL and use that to append a similar message warning about this being the documentation for the in-development version.

**Comment by simonw** [comment]
Here's a jQuery recipe that seems to do the right thing:
```javascript
jQuery(function ($) {
  // If this is a /latest/ doc page, show banner linking to /stable/
  if (!/\/latest\//.test(location.pathname)) {
    return;
  }
  var stableUrl = location.pathname.replace("/latest/", "/stable/");
  // Check it's not a 404
  fetch(stableUrl, { method: "HEAD" }).then((response) => {
    if (response.status == 200) {
      var warning = $(
        `<div class="admonition warning">
           <p class="first admonition-title">Note</p>
           <p class="last">
             This documentation covers the <strong>development version</strong> of Datasette.</p>
             <p>See <a href="${stableUrl}">this page</a> for the current stable release.
           </p>
        </div>`
      );
      warning.find("a").attr("href", stableUrl);
      var body = $("div.body");
      if (!body.length) {
        body = $("div.document");
      }
      body.prepend(warning);
    }
  });
});
```

**Comment by astrojuanlu** [comment]
Or you can use https://sphinx-version-warning.readthedocs.io/! 😄

**Comment by simonw** [comment]
D'oh! Just shipped my fix here: https://docs.datasette.io/en/latest/

<img width="994" alt="image" src="https://user-images.githubusercontent.com/9599/150434433-e2f0d472-77a8-430b-88e5-f22e2c6e8ef0.png">

**Comment by simonw** [comment]
> https://sphinx-version-warning.readthedocs.io/ looks like it can show a banner for "You are looking at v0.36 but you should be looking at 0.40" but doesn't hand the case I need here which is "you are looking at /latest/ but you should be looking at /stable/".

Correction! That tool DOES support that, as can be seen in their example configuration for their own documentation:

https://github.com/humitos/sphinx-version-warning/blob/a82156c2ea08e5feab406514d0ccd9d48a345f48/docs/conf.py#L32-L38

```python
versionwarning_messages = {
    'latest': 'This is a custom message only for version "latest" of this documentation.',
}
versionwarning_admonition_type = 'tip'
versionwarning_banner_title = 'Tip'
versionwarning_body_selector = 'div[itemprop="articleBody"]'
```

**Comment by simonw** [comment]
Got a couple of TILs out of this:

- [Promoting the stable version of the documentation using rel=canonical](https://til.simonwillison.net/readthedocs/documentation-seo-canonical)
- [Linking from /latest/ to /stable/ on Read The Docs](https://til.simonwillison.net/readthedocs/link-from-latest-to-stable)

**Comment by simonw** [comment]
This broke when I upgraded to the Furo theme.

**Comment by simonw** [comment]
That didn't work, because `jQuery` isn't yet defined that high up the template.

**Comment by simonw** [comment]
Still getting this error:

<img width="537" alt="image" src="https://user-images.githubusercontent.com/9599/227811947-a35a6758-cf94-4196-89ce-85ae2f48ab06.png">

Weird because `jQuery` is present in the devtools console.

**Comment by simonw** [comment]
ChatGPT prompt:

> ```
> jQuery(function ($) {
>   // Show banner linking to /stable/ if this is a /latest/ page
>   if (!/\/latest\//.test(location.pathname)) {
>     return;
>   }
>   var stableUrl = location.pathname.replace("/latest/", "/stable/");
>   // Check it's not a 404
>   fetch(stableUrl, { method: "HEAD" }).then((response) => {
>     if (response.status == 200) {
>       var warning = $(
>         `<div class="admonition warning">
>            <p class="first admonition-title">Note</p>
>            <p class="last">
>              This documentation covers the <strong>development version</strong> of Datasette.</p>
>              <p>See <a href="${stableUrl}">this page</a> for the current stable release.
>            </p>
>         </div>`
>       );
>       warning.find("a").attr("href", stableUrl);
>       $("article[role=main]").prepend(warning);
>     }
>   });
> });
> 
> Rewrite this to use vanilla JavaScript, no jQuery
> ```

Got back:

```javascript
document.addEventListener("DOMContentLoaded", function() {
  // Show banner linking to /stable/ if this is a /latest/ page
  if (!/\/latest\//.test(location.pathname)) {
    return;
  }
  var stableUrl = location.pathname.replace("/latest/", "/stable/");
  // Check it's not a 404
  fetch(stableUrl, { method: "HEAD" }).then((response) => {
    if (response.status === 200) {
      var warning = document.createElement("div");
      warning.className = "admonition warning";
      warning.innerHTML = `
        <p class="first admonition-title">Note</p>
        <p class="last">
          This documentation covers the <strong>development version</strong> of Datasette.
        </p>
        <p>
          See <a href="${stableUrl}">this page</a> for the current stable release.
        </p>
      `;
      var mainArticle = document.querySelector("article[role=main]");
      mainArticle.insertBefore(warning, mainArticle.firstChild);
    }
  });
});
```

**Comment by simonw** [comment]
It's working again now: https://docs.datasette.io/en/latest/sql_queries.html
