### ISSUE TITLE
Support WITH query 

### ISSUE THREAD

**Issue by wsxiaoys** [simonw/datasette#161]
Currently datasettle failed with error message: Statement must begin with SELECT

Example query
```sql
WITH RECURSIVE
  cnt(x) AS (
     SELECT 1
     UNION ALL
     SELECT x+1 FROM cnt
      LIMIT 1000000
  )
SELECT x FROM cnt;
```

**Comment by simonw** [comment]
Seems like a reasonable thing for us to support.

**Comment by wsxiaoys** [comment]
It's not throwing the validation error anymore, but i still cannot run following with query:
```
WITH RECURSIVE cnt(x) AS (SELECT 1 UNION ALL SELECT x+1 FROM cnt LIMIT 10) SELECT x FROM cnt;
```

I got `near "WITH": syntax error`.

**Comment by simonw** [comment]
That might mean your version of SQLite doesn't support that syntax. Unfortunately the version bundled with Python is a bit old - the one built by the Dockerfile in this repo should handle it though.

**Comment by wsxiaoys** [comment]
You're right..got this resolved after upgrading the sqlite version.

Thanks you!
