### ISSUE TITLE
Document the querystring argument for setting a different time limit

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#163]
http://datasette.readthedocs.io/en/latest/sql_queries.html#query-limits

Need to explain why this is useful too.

**Comment by mroswell** [comment]
I'm visiting old issues for context while learning datasette. Let me know if okay to make the occasional comment like this one.
querystring argument now located at:
https://docs.datasette.io/en/latest/settings.html#sql-time-limit-ms

**Comment by simonw** [comment]
Comments welcome!
