### ISSUE TITLE
Configuration directory mode does not pick up other file extensions than .db

### ISSUE THREAD

**Issue by dnsos** [simonw/datasette#1646]
Hello, I've been trying to run Datasette with the [configuration directory mode](https://docs.datasette.io/en/stable/settings.html#configuration-directory-mode) with a structure such as this one:

```plain
some-directory/
    example.sqlite3
    another-example.db
    one-more.custom
    [...]
```

(In my scenario I can't just change the filename extension without other problems arising)

Now databases with the `.sqlite3` or the custom filename extension are ignored by Datasette in this case. I'm aware that the docs state that a `.db` extension is required, but I was wondering if there is a reason for restricting this or any workaround available? When I run `datasette example.sqlite3` or `datasette one-more.custom` the databases are served by Datasette without a problem.

**Comment by mustafa0x** [comment]
I'm affected by this as well. Would be nice to be able to pass in an extension, eg `--extension=sqlite3`.

**Comment by simonw** [comment]
Adding `.sqlite3` to this feature makes sense to me.

I don't think it's worth having a `--extensión` option - it's possible right now to write a Datasette plugin that loads additional databases on startup, there's an example of how to do that in the source code for https://github.com/simonw/datasette-upload-dbs

**Comment by simonw** [comment]
Updated documentation: https://docs.datasette.io/en/latest/settings.html#configuration-directory-mode
