### ISSUE TITLE
Research an upgrade to CodeMirror 6

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#1796]
There are still a bunch of bugs in CodeMirror 5 that affect various mobile browsers - see Datasette Discord report here: https://discord.com/channels/823971286308356157/823971286941302908/1013878624992108645

https://user-images.githubusercontent.com/9599/187349269-7b7c0c8c-3894-4810-82f0-de7c1eb940b3.mp4

**Comment by simonw** [comment]
I wrote upgrade instructions for CodeMirror here: https://docs.datasette.io/en/0.62/contributing.html#upgrading-codemirror

See also:
- #948

But... those instructions don't work any more, because they start with downloading the CodeMirror zip - but according to https://codemirror.net/docs/migration/

> The 5.x library was distributed as UMD modules, which could either be loaded directly with <script> tags or bundled as CommonJS modules. The new version exposes only modules, which will require some kind of build step before you can use them.

**Comment by simonw** [comment]
Also relevant: Wikimedia are upgrading to CodeMirror 6 partly because of improved mobile support: https://phabricator.wikimedia.org/T259059

**Comment by simonw** [comment]
I wonder if CodeMirror 6 would be a good time to revisit this:
- #1614

**Comment by fgregg** [comment]
@simonw is this issue closed by #1893?
