### ISSUE TITLE
Static files not served

### ISSUE THREAD

**Issue by frafra** [simonw/datasette#1814]
Folder structure:

```
bibliography/
bibliography/static-files
bibliography/static-files/styles.css
bibliography/bibliography.db
bibliography/metadata.json
bibliography/settings.json
```

```
$ cat bibliography/settings.json 
{
  "suggest_facets": false,
  "truncate_cells_html": 1000,
  "static": "assets:static-files/"
}
```

File `/assets/styles.css` is not found (HTTP 404, `Database not found: assets`).

Using datasette revision d0737e4de51ce178e556fc011ccb8cc46bbb6359.

**Comment by simonw** [comment]
The `settings.json` file can only be used with settings that are set using `--setting name value` - the full list of those is here: https://docs.datasette.io/en/stable/settings.html

The `--static` option works differently. In configuration directory mode you can skip it entirely and instead have a `/static/` folder - so your directory structure would look like this:

```
bibliography/static/styles.css
```
And then when you run `datasette bibliography/` the following URL will work:

    http://127.0.0.1:8001/static/styles.css

**Comment by simonw** [comment]
It might have been useful for Datasette to show an error when started against a `settings.json` file that contains an invalid setting though.
