### ISSUE TITLE
render_cell documentation example doesn't match the method signature

### ISSUE THREAD

**Issue by pjamargh** [simonw/datasette#1826]
Open Datasette stable doc at https://docs.datasette.io/en/stable/plugin_hooks.html?highlight=render_cell#render-cell-row-value-column-table-database-datasette

render_cell plugin hook method signature is `render_cell(row, value, column, table, database, datasette)`, the example shown inline uses `render_cell(value)`.

![image](https://user-images.githubusercontent.com/66709385/192674691-34265b81-6cdd-41d2-8424-aa12f8bc8c94.png)

**Comment by simonw** [comment]
This is deliberate. The Datasette plugin system allows you to specify only a subset of the parameters for a hook - in this example, only the `value` is needed so the others can be omitted.

There's a note about this at the very top of that documentation page: https://docs.datasette.io/en/stable/plugin_hooks.html#plugin-hooks

> When you implement a plugin hook you can accept any or all of the parameters that are documented as being passed to that hook.
> 
> For example, you can implement the `render_cell` plugin hook like this even though the full documented hook signature is `render_cell(value, column, table, database, datasette)`:
> ```python
> @hookimpl
> def render_cell(value, column):
>     if column == "stars":
>         return "*" * int(value)
> ```

**Comment by simonw** [comment]
Though now I notice that the copy right there needs to be updated to reflect the new `row` parameter to `render_cell`!

**Comment by pjamargh** [comment]
I'm glad the bug report served some purpose. Frankly I just needed the
method signature, that is why the documentation you mention wasn't read.
