### ISSUE TITLE
proposal new option to disable user agents cache

### ISSUE THREAD

**Issue by stefanocudini** [simonw/datasette#186]
I think it would be very useful for debugging an option of adding headers to http replies

```
Cache-Control: no-cache 
```

especially in the html output

**Comment by simonw** [comment]
Hah, this is exactly the opposite of datasette's default approach to caching, which is to cache everything for as long as possible.

I don't think we'll need to add `Cache-Control: no-cache` headers provided we instead set it up so you can turn off Datasette's caching.

**Comment by simonw** [comment]
We actually have this already:

https://github.com/simonw/datasette/blob/012fc7c5cd3e9160c9a4c19cc964253e97fb054a/datasette/cli.py#L253-L255

You can disable the cache headers using the `datasette --debug` option.

**Comment by stefanocudini** [comment]
--debug is perfect tnk
