### ISSUE TITLE
SQL query field can't begin by a comment

### ISSUE THREAD

**Issue by CharlesNepote** [simonw/datasette#1860]
![image](https://user-images.githubusercontent.com/562352/198085197-f26fcd61-4dac-4ca4-a346-e70f88a30ecc.png)

SQL comments are **very** useful to explain the meaning of the query. It's currently impossible to put it at the beginning of the field as seen on the screen capture: it leads to an error: `Statement must be a SELECT`.

It would be great to make it possible because:
* as the request is the title of the page:
  * it eases the search with search engines
  * it eases the search in the browsers' url field
* it acts as a kind of title: the global meaning of the query is immediately understandable
* some tools, such as Slack, are shortening long URLs and displaying the beginning of the URLs (eg. `https://example.org/products?sql=select+%28length%28data_quality_errors_ta[...]+%21%3D+%22%22+group+by+NB_of_issues+order+by+NB_of_issues+desc+limit+200`)

Beginning a query with a comment is possible with SQLite.

**Comment by CharlesNepote** [comment]
I guess the issue is here: https://github.com/simonw/datasette/blob/9676b2deb07cff20247ba91dad3e84a4ab0b00d1/datasette/utils/__init__.py#L209

Here is a working regexp allowing it:
```diff
-    re.compile(r"^select\b"),
+    re.compile(r"^\s*(/\*.+?(?=\*/)\*/\s*)*select"),
```
`^\s*`: beginning by 0 or an infinite number of \s (spaces, tabs, newlines...)
`(/\*.+?(?=\*/)\*/\s*)*`: 0 or an infinite number of chars beginning by `/*` and ending to the next occurrence of `*/` followed by 0 or an infinite number of \s

You can play with the regexp here: https://regex101.com/r/aESXDL/3

**Comment by simonw** [comment]
Yeah we should fix this.

https://www.sqlite.org/lang_comment.html - SQLite also supports `-- style` comments.

**Comment by simonw** [comment]
I'm experimenting with this:
```python
# Allow SQL to start with a /* */ or -- comment
comment_re = (
    # Start of string, then any amount of whitespace
    r'^(\s*' +
    # Comment that starts with -- and ends at a newline
    r'(?:\-\-.*?\n\s*)' +
    # Comment that starts with /* and ends with */
    r'|(?:/\*[\s\S]*?\*/)' + 
    # Whitespace
    r')*\s*'
)

allowed_sql_res = [
    re.compile(comment_re + r"select\b"),
    re.compile(comment_re + r"explain\s+select\b"),
    re.compile(comment_re + r"explain\s+query\s+plan\s+select\b"),
    re.compile(comment_re + r"with\b"),
    re.compile(comment_re + r"explain\s+with\b"),
    re.compile(comment_re + r"explain\s+query\s+plan\s+with\b"),
]
```
This should allow any number of comments of either type as a suffix to the allowed SQL patterns.

Needs extensive unit tests!

I'm not massively worried if it has a flaw in it though, since this is part of Datasette's defense in depth: if a non-SELECT query sneaks through it still shouldn't be able to cause any damage as the database connection is read-only or immutable.

**Comment by simonw** [comment]
Here are the new tests: https://github.com/simonw/datasette/blob/55a709c480a1e7401b4ff6208f37a2cf7c682183/tests/test_utils.py#L170-L175

**Comment by simonw** [comment]
I'm never 100% sure how to tell if a regular expression includes a nasty denial of service attack - are there any inputs that could cause this new regex to execute in quadratic time or similar?

**Comment by simonw** [comment]
That's deployed to https://latest.datasette.io/ now - some examples:

- https://latest.datasette.io/fixtures?sql=--+one+kind+of+comment%0D%0Aselect+*+from+searchable
- https://latest.datasette.io/fixtures?sql=%2F*+Multi%0D%0A++line+comment+*%2F%0D%0Aselect+*+from+searchable
- https://latest.datasette.io/fixtures?sql=%2F*+Both+kinds+*%2F%0D%0A--+of+comment%0D%0A%2F*+and+more+*%2F%0D%0A--+and+more+and+more%0D%0Aselect+*+from+searchable

**Comment by CharlesNepote** [comment]
Sorry I forgot the `-- comments like that`.

I'm afraid there is an issue in your regexp, see: https://regex101.com/r/pyubJf/1

I guess I can fix it.

**Comment by CharlesNepote** [comment]
Here is my suggestion:

`^\s*((?:\-\-.*?\n\s*)|(?:/\*.*?(?=\*/)\*/\s*))*select\b`

See the following test: https://regex101.com/r/Doeqqa/1

And here I played all your tests: https://regexr.com/713ir

**Comment by simonw** [comment]
Hah, I just came up with this one:

`^\s*((?:\-\-.*?\n\s*)|(?:\/\*((?!\*\/)[\s\S])*\*\/)\s*)*\s*select\b`

**Comment by simonw** [comment]
Here's yours on Debuggex: https://www.debuggex.com/r/HjdJryTy9ezGsuWK

<img width="889" alt="image" src="https://user-images.githubusercontent.com/9599/198373230-c36d87f8-69e6-4abe-8867-4d9ba0b57698.png">

**Comment by simonw** [comment]
I think mine has a better pattern for handling `/* ... anything in here that isn't */ ... */`

**Comment by simonw** [comment]
The new code is now live at https://latest.datasette.io/fixtures
