### ISSUE TITLE
SITE-BUSTING ERROR: "render_template() called before await ds.invoke_startup()"

### ISSUE THREAD

**Issue by mroswell** [simonw/datasette#1872]
1. My https://list.saferdisinfectants.org/disinfectants/listN page (linked from https://SaferDisinfectants.org ) has been running beautifully for a year and a half, including a GitHub Actions workflow that's been routinely updating the database.

2. I received a recent report that the list page is down. I don't know when it went down, but the content is replaced with: "render_template() called before await ds.invoke_startup()"

3. The local datasette repo runs without incident.

4. The site is hosted on vercel, linked to my github repo. Perhaps  some vercel changes were made, but not by anyone on our side. Here is a screenshot of the current project settings:

<img width="877" alt="Screen Shot 2022-10-29 at 9 23 30 PM" src="https://user-images.githubusercontent.com/192568/198859474-341a5504-88b8-452d-bd06-e988cbe75e6c.png">

Here a screenshot of the latest deployment status:
<img width="1351" alt="Screen Shot 2022-10-29 at 10 19 21 PM" src="https://user-images.githubusercontent.com/192568/198859641-ad3d99ba-a41d-4b98-88f6-e3a01fe9f238.png">

This is my repository:
https://github.com/mroswell/list-N
(I notice: datasette==0.59 in my requirements.txt file)

Because it's been long while since I actively worked on this or any other datasette project, I forget a lot of what I knew at one point. Perhaps some configuration file could be missing? Or perhaps I just need to know the right incantation to add to that vercel settings page. 

Help is welcome as the nonprofit org is soon hosting its annual conference, and we'd love to have the page working again.

**Comment by mroswell** [comment]
should this issue be under https://github.com/simonw/datasette-publish-vercel/issues ?

Perhaps I just need to update: 
datasette-publish-vercel==0.11
in requirements.txt?
 
 I'll try that and see what happens...

**Comment by mroswell** [comment]
I updated datasette-publish-vercel to  0.14.2 in requirements.txt

And the site is back up!

Is there a way that we can get some sort of notice when something like this will have critical impact on website function?

**Comment by simonw** [comment]
Good spot fixing that!

Sorry about this - it was a change in Datasette 0.63 which should have been better called out.

My goal for Datasette 1.0 (which I aim to have out by the end of the year) is to introduce a formal process for avoiding problems like this, with very clear documentation when something like this might happen.
