### ISSUE TITLE
Merge 1.0-dev branch back to main

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#1892]
I'm committed enough to the 1.0 work now that I'm ready for the `main` branch to reflect that instead.

If I need to make any dot-releases against 0.63 I can do those from a branch.

**Comment by simonw** [comment]
I'll do this after the 1.0a0 release:
- #1708

**Comment by simonw** [comment]
One slight concern: https://latest.datasette.io/ will increasingly reflect a version that isn't the most recent production release.

I might setup https://stable.datasette.io/ as a demo instance of the most recent non-alpha release to compensate for that.

**Comment by ocdtrekkie** [comment]
I have no particular point, I just want to say being around for the 1.0 release of Datasette seems historic and legendary to witness.
