### ISSUE TITLE
Serve schema JSON to the SQL editor to enable autocomplete

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#1897]
See:
- https://github.com/simonw/datasette/issues/1893#issuecomment-1317831555

**Comment by simonw** [comment]
Here's where the schema is hard-coded at the moment: https://github.com/simonw/datasette/blob/00e233d7a7f6443cb95fb5227c23580c48551cad/datasette/templates/_codemirror_foot.html#L2-L7

I figured out how to extract that data from the `_internal` table in this comment: https://github.com/simonw/datasette/pull/1893#issuecomment-1317475720

Although that used JSON functions which may (in a real edge-case) not be available in the version of SQLite that Datasette is running on, so probably going to use a regular SQL query and then assemble the JSON separately.

**Comment by simonw** [comment]
I'm going to call this `table_columns` in the template context (because `schema` might mean `CREATE TABLE ...`.

**Comment by simonw** [comment]
In terms of permissions: if you have `execute-sql` permission for a database then it's OK for you to see the table columns for that database.

**Comment by simonw** [comment]
```python
async def _table_columns(datasette, database_name):
    internal = datasette.get_database("_internal")
    result = await internal.execute(
        "select table_name, name from columns where database_name = ?",
        [database_name],
    )
    table_columns = {}
    for row in result.rows:
        table_columns.setdefault(row["table_name"], []).append(row["name"])
    return table_columns
```

**Comment by simonw** [comment]
Just noticed that this isn't including views, which it should.

**Comment by simonw** [comment]
Views aren't currently available in the `_internal` schema.

**Comment by simonw** [comment]
I decided to just go for the view names, not their columns.

**Comment by bgrins** [comment]
Are you tracking the change to send the JSON over to the frontend separately or was that part of this? Something like this is probably pretty close https://github.com/bgrins/datasette/commit/8431c98850c7a552dbcde2a4dd0c3dc942a97d25#diff-0c93232bfd5477eeac96382e52769108b41433d960d5277ffcccf2f464e60abdR9

**Comment by simonw** [comment]
One of the big changes still left to do for Datasette 1.0 is to unify the JSON representation with the context psssed to the templates (via an `?_extra=` mechanism to add extra context needed by the HTML templates), because a goal for 1.0 is for the template context to be a documented API contract such that custom templates won't break with future releases.

As such I expect to do quite a bit of refactoring and cleanup on how the template context works later on.
