### ISSUE TITLE
Clicking within the CodeMirror area below the SQL (i.e. when there's only a single line) doesn't cause the editor to get focused 

### ISSUE THREAD

**Issue by bgrins** [simonw/datasette#1899]
After the upgrade to 6 (#1893) I noticed this. I think it's because we're doing overflow:hidden to accomplish the CSS resizer.

When there's a single line of SQL there's a gap below that line where clicking doesn't do anything. It should focus at the end of the line.

**Comment by bgrins** [comment]
This is one way to fix it

```patch
r.html
diff --git a/datasette/static/cm-editor-6.0.1.js b/datasette/static/cm-editor-6.0.1.js
index c1fd2ab..68cf398 100644
--- a/datasette/static/cm-editor-6.0.1.js
+++ b/datasette/static/cm-editor-6.0.1.js
@@ -22,7 +22,14 @@ export function editorFromTextArea(textarea, conf = {}) {
   // https://github.com/codemirror/lang-sql#user-content-sqlconfig.tables
   let view = new EditorView({
     doc: textarea.value,
+
     extensions: [
+      EditorView.theme({
+        ".cm-content": {
+          // Height on cm-content ensures the editor is focusable by clicking beyond the height of the text
+          minHeight: "70px",
+        },
+      }),
       keymap.of([
         {
           key: "Shift-Enter",
diff --git a/datasette/templates/_codemirror.html b/datasette/templates/_codemirror.html
index dea4710..c4629ae 100644
--- a/datasette/templates/_codemirror.html
+++ b/datasette/templates/_codemirror.html
@@ -4,7 +4,6 @@
   .cm-editor {
     resize: both;
     overflow: hidden;
-    min-height: 70px;
     width: 80%;
     border: 1px solid #ddd;
   }
```

I don't love it but it seems to work for the default case. You can still retrigger the bug by resizing the editor to be > 70px high.

The other approach would be to listen for a click on that empty region and move focus to the editor, or something

**Comment by bgrins** [comment]
Another idea would be to just not set a min-height and allow the 1 line input to be 1 line heigh

**Comment by simonw** [comment]
I can't actually remember where that `min-height: 70px` came from. I just tried without it and it seems fine - especially since any time you add a newline in the editor it increases its height to fit.

**Comment by simonw** [comment]
Demo: https://latest.datasette.io/fixtures
