### ISSUE TITLE
Incorrect link from the API explorer to the JSON API documentation

### ISSUE THREAD

**Issue by davidbgk** [simonw/datasette#1929]
I installed `datasette==1.0a1`.

When I go to http://127.0.0.1:8001/-/api I have a link: `Use this tool to try out the [Datasette API](https://docs.datasette.io/en/1.0a1/json_api.html).` but that documentation page does not exist.

I'm not sure where it has to be fixed, should it link to the stable page https://docs.datasette.io/en/stable/json_api.html , the latest one https://docs.datasette.io/en/latest/json_api.html#the-json-write-api or would it be more appropriated to deploy documentation for the `1.0a1` version?

**Comment by simonw** [comment]
Yeah I should deploy the docs for the alpha versions (the intention is that the docs exactly match the release you are using), thanks for spotting that.

**Comment by simonw** [comment]
I can do that on this page: https://readthedocs.org/projects/datasette/versions/?version_filter=1.0

<img width="861" alt="image" src="https://user-images.githubusercontent.com/9599/206003351-1a480f9c-ffc3-413a-a7c8-ad138c25a2f6.png">

**Comment by simonw** [comment]
https://docs.datasette.io/en/1.0a1/json_api.html 👍
