### ISSUE TITLE
Broken link to live demo in Getting started docs

### ISSUE THREAD

**Issue by lbellomo** [simonw/datasette#1966]
The link in [Play with a live demo in Getting started](https://github.com/simonw/datasette/blob/main/docs/getting_started.rst#play-with-a-live-demo) to [https://fivethirtyeight.datasettes.com/fivethirtyeight](https://fivethirtyeight.datasettes.com/fivethirtyeight) is broken and the datasette is no longer working (maybe due to the end of the free tier).

**Comment by simonw** [comment]
It's working again now - not sure what happened there, I was paying for Heroku for that already.
