### ISSUE TITLE
Error: Invalid setting 'hash_urls' in settings.json in 0.64.1

### ISSUE THREAD

**Issue by mlaparie** [simonw/datasette#2023]
On a Debian machine, using datasette 0.64.1 installed with `pip3`, I am getting a `datasette[114272]: Error: Invalid setting 'hash_urls' in settings.json` in `journalctl -xe`. The same settings work on 0.54.1 on another Debian server.

This is my `settings.json`:

```json
{
    "default_page_size": 200,
    "max_returned_rows": 8000,
    "num_sql_threads": 3,
    "sql_time_limit_ms": 1000,
    "default_facet_size": 30,
    "facet_time_limit_ms": 200,
    "facet_suggest_time_limit_ms": 50,
    "hash_urls": false,
    "allow_facet": true,
    "allow_download": true,
    "suggest_facets": true,
    "default_cache_ttl": 5,
    "default_cache_ttl_hashed": 31536000,
    "cache_size_kb": 0,
    "allow_csv_stream": true,
    "max_csv_mb": 100,
    "truncate_cells_html": 2048,
    "force_https_urls": false,
    "template_debug": false,
    "base_url": "/pclim/db/"
}
```

This looks ok to me. Would you have any ideas?

**Comment by cldellow** [comment]
I think this feature was removed in Datasette 0.61 and moved to a plugin. People who want hashed URLs can use the [datasette-hashed-urls](https://docs.datasette.io/en/stable/performance.html#performance-hashed-urls) plugin to achieve the same affect.

It looks like you're trying to disable hashed urls, so I think you can just remove that config setting and things will work.

**Comment by mlaparie** [comment]
Thanks for confirming my doubts! I removed it after opening this issue, yup, then had another issue with `default_cache_ttl_hashed` which I assume was removed at the same time. Sorry for not trying that before opening the issue.
