### ISSUE TITLE
How to use Datasette with apache webserver on GCP?

### ISSUE THREAD

**Issue by gk7279** [simonw/datasette#2030]
Hi Simon and Datasette team-

I have installed apache2 webserver inside GCP VM using apt.

I can see my "Hello World" index.html if I use the external IP of this GCP in a browser.

However, when I try to run datasette with different combinations of -h and -p, I am still unable to access the webpage.

I cannot invest Docker on this VM.

Any pointers to use datasette with already existing apache2 webserver on GCP is appreciated.

Thanks.

**Comment by dmick** [comment]
@gk7279, you had asked in a separate bug about how to redirect web servers in general.  The datasette docs actually have pretty good information on this for both nginx and apache2: https://docs.datasette.io/en/stable/deploying.html#running-datasette-behind-a-proxy

**Comment by gk7279** [comment]
Thanks @dmick  . I chose to create a firewall rule under my GCP to open the port of interest and datasette works.
