### ISSUE TITLE
Tables starting with an underscore should be treated as hidden

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#2104]
Plugins can then take advantage of this pattern, for example:
- https://github.com/simonw/datasette-auth-tokens/pull/8

**Comment by simonw** [comment]
Relevant code: https://github.com/simonw/datasette/blob/0f7192b6154edb576c41b55bd3f2a3f53e5f436a/datasette/database.py#L391-L451

**Comment by asg017** [comment]
For filtering virtual table's "shadow tables" (ex the FTS5 _content and most the spatialite tables),  you can use `pragma_table_list` (first appeared in SQLite 3.37 (2021-11-27), which has a `type` column that calls out `type="shadow"` tables https://www.sqlite.org/pragma.html#pragma_table_list

**Comment by simonw** [comment]
We really need this for Datasette Cloud, we have `_hidden_but_not_hidden` tables all over the place!

**Comment by simonw** [comment]
Had to figure out how to run a LIKE query with a literal `_` in it - this is the syntax:
```sql
or name like '\_%' escape '\'
```

**Comment by simonw** [comment]
There isn't any documentation on hidden tables right now, fixing that.

**Comment by simonw** [comment]
> For filtering virtual table's "shadow tables" (ex the FTS5 _content and most the spatialite tables), you can use `pragma_table_list` (first appeared in SQLite 3.37 (2021-11-27), which has a `type` column that calls out `type="shadow"` tables

Neat!

![CleanShot 2024-03-07 at 00 01 55@2x](https://github.com/simonw/datasette/assets/9599/7d53faa4-9c1f-41d6-9aac-d126f6feed37)

Aside: Datasette doesn't allow `select * from pragma_table_list()` now but I can fix that easily.

**Comment by simonw** [comment]
Added new documentation listing all of the different types of hidden table here: https://docs.datasette.io/en/latest/pages.html#hidden-tables
