### ISSUE TITLE
prepare_context() plugin hook

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#227]
This would be called with the context dictionary before each template is rendered. It would have the opportunity to modify that context.

**Comment by simonw** [comment]
Maybe this should have a second argument indicating which codepath was being handled. That way plugins could say "only inject this extra context variable on the row page".

**Comment by simonw** [comment]
A better way to do this would be with many different plugin hooks, one for each view.

**Comment by simonw** [comment]
What if the context needs to make await calls?

One possible option: plugins can either manipulate the context in place OR they can return an awaitable. If they do that, the caller will await it.

**Comment by simonw** [comment]
Should this differentiate between preparing the data to be sent back as JSON and preparing the context for the template?

**Comment by simonw** [comment]
Maybe prepare_table_data() vs prepare_table_context()

**Comment by carlmjohnson** [comment]
I'm diving back into https://salaries.news.baltimoresun.com and what I really want is the ability to inject the request into my context.

**Comment by simonw** [comment]
I think the [extra_template_vars()](https://datasette.readthedocs.io/en/stable/plugins.html#extra-template-vars-template-database-table-view-name-request-datasette) hook covers this.
