### ISSUE TITLE
Block or rate limit based on User Agent?

### ISSUE THREAD

**Issue by louispotok** [simonw/datasette#2361]
I'm getting traffic from `facebookexternalhit` user agents -- it's not a huge amount (2req/s) but the bill starts to add up. From what I can tell, this is the [facebook crawler](https://developers.facebook.com/docs/sharing/webmasters/crawler) which does not mention `robots.txt` (vs [FacebookBot](https://developers.facebook.com/docs/sharing/bot) which seems to respect it. [This SO thread](https://stackoverflow.com/questions/63330082/facebookexternalhit-1-1-bot-excessive-requests-need-to-slow-down) claims that the Crawler doesn't respect `robots.txt`, so `datasette-block-robots` doesn't seem to solve this.

Is there another way to block or rate limit a given user agent in datasette? I'm deploying on Google Cloud if that's relevant. Thanks!

**Comment by simonw** [comment]
I think this feature is out-of-scope for Datasette core, but it could make a great plugin. It would need to use the ASGI middleware plugin, then implement its own state tracking for rate limiting against IP.

It could even use an in-memory SQLite database for the rate limit counters, which could be pretty neat.
