### ISSUE TITLE
Proposal: add new `DATASETTE_SSL_KEYFILE` and `DATASETTE_SSL_CERTFILE` env vars for `--ssl-keyfile` and `--ssl-certfile`

### ISSUE THREAD

**Issue by asg017** [simonw/datasette#2422]
An alternative to using the `--ssl-keyfile` and `--ssl-certfile` flags. 

Could also be a part of `datasette.yaml` I guess?

**Comment by simonw** [comment]
A few other existing environment variables:

https://github.com/simonw/datasette/blob/0bc6a2af89a2201d55650c47f8cdbf8aa26255d4/datasette/cli.py#L234

https://github.com/simonw/datasette/blob/0bc6a2af89a2201d55650c47f8cdbf8aa26255d4/datasette/cli.py#L424

https://github.com/simonw/datasette/blob/0bc6a2af89a2201d55650c47f8cdbf8aa26255d4/datasette/cli.py#L88

https://github.com/simonw/datasette/blob/0bc6a2af89a2201d55650c47f8cdbf8aa26255d4/datasette/plugins.py#L37

https://github.com/simonw/datasette/blob/0bc6a2af89a2201d55650c47f8cdbf8aa26255d4/datasette/plugins.py#L60

**Comment by simonw** [comment]
So we've been using `DATASETTE_` prefix already, let's stick with that.

**Comment by simonw** [comment]
I'm going to document these in a new section on https://docs.datasette.io/en/latest/cli-reference.html#datasette-serve

**Comment by simonw** [comment]
New docs are live here: https://docs.datasette.io/en/latest/cli-reference.html#environment-variables
