### ISSUE TITLE
Escaping named parameters in canned queries

### ISSUE THREAD

**Issue by philroche** [simonw/datasette#254]
Thank you very much for this project.

I have created some canned queries but some of the filters include a colon eg. "com.ubuntu.cloud:server:18.04:amd64". When saved these colons are parsed as named parameters. 

Is there a way to escape colons in a canned query?

**Comment by simonw** [comment]
Do you have an example I can look at?

I think I have a possible route for fixing this, but it's pretty tricky (it involves adding a full SQL statement parser, but that's needed for some other potential improvements as well).

In the meantime, is this causing actual errors for you or is it more of an inconvenience (form fields being displayed that don't actually do anything)?

Another potential solution here could be to allow canned queries toniptionally declare their parameters in metadata.json

**Comment by philroche** [comment]
An example deployment @ https://datasette-zkcvlwdrhl.now.sh/simplestreams-270f20c/cloudimage?content_id__exact=com.ubuntu.cloud%3Areleased%3Adownload

It is not causing errors, more of an inconvenience. I have worked around it using a `like` query instead.

**Comment by simonw** [comment]
Got it, this seems to trigger the problem: https://datasette-zkcvlwdrhl.now.sh/simplestreams-270f20c?sql=select+*+from+cloudimage+where+%22content_id%22+%3D+%22com.ubuntu.cloud%3Areleased%3Adownload%22+order+by+id+limit+101&p0=com.ubuntu.cloud%3Areleased%3Adownload

**Comment by philroche** [comment]
This has now been resolved and is not present in current version of datasette. 

Sample query @simonw mentioned now returns as expected. 

https://aggreg8streams.tinyviking.ie/simplestreams?sql=select+*+from+cloudimage+where+%22content_id%22+%3D+%22com.ubuntu.cloud%3Areleased%3Adownload%22+order+by+id+limit+10
