### ISSUE TITLE
Documentation for URL hashing, redirects and cache policy

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#267]
See my comments on #258 for a starting point

**Comment by simonw** [comment]
See also #286

**Comment by annapowellsmith** [comment]
Looks to me like hashing, redirects and caching were documented as part of https://github.com/simonw/datasette/commit/788a542d3c739da5207db7d1fb91789603cdd336#diff-3021b0e065dce289c34c3b49b3952a07 - so perhaps this can be closed? :tada:

**Comment by simonw** [comment]
Yes this is definitely documented now https://datasette.readthedocs.io/en/stable/performance.html
