### ISSUE TITLE
Ability to plot a simple graph

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#27]
Might be as simple as: pick he type of chart (bar, line) and then pick the column for the X axis and the column for the Y axis. Maybe also allow a pie chart. It’s up to the user to come up with SQL that gets the right values.

**Comment by simonw** [comment]
https://github.com/frappe/charts perhaps

**Comment by rgieseke** [comment]
If Data Package metadata gets adopted (#105) the views spec work might also be worth a look:

http://frictionlessdata.io/specs/views/

http://datahub.io/docs/features/views

**Comment by simonw** [comment]
I consider this handled by https://github.com/simonw/datasette-vega
