### ISSUE TITLE
Figure out a way to have /-/version return current git commit hash

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#273]
https://fivethirtyeight.datasettes.com/-/versions reports Datasette version `0.21`

This isn't actually correct. The deploy script for that site actually deploys current master using `https://github.com/simonw/datasette/archive/master.zip`: https://github.com/simonw/fivethirtyeight-datasette/blob/66b4b0dfedd7237bc8c02d3e26d905bca7b84069/Dockerfile#L9

Ideally this would show the current commit hash, but I'm not at all sure if it's possible to derive that from `pip install https://github.com/simonw/datasette/archive/master.zip`. Is there another mechanism that could be used to reliably `pip install` current master but still provide access to the most recent commit hash?

**Comment by rgieseke** [comment]
Shouldn't [versioneer](https://github.com/warner/python-versioneer) do that?

E.g. 0.21+2.g1076c97

You'd need to install via `pip install git+https://github.com/simow/datasette.git` though, this does a temp git clone.

**Comment by simonw** [comment]
That looks great. I don't think it's possible to derive the current commit version from the .zip downloaded directly from GitHub, so needing to pip install via git+https feels reasonable to me.
