### ISSUE TITLE
Travis should push tagged images to Docker Hub for each release

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#329]
https://sebest.github.io/post/using-travis-ci-to-build-docker-images/

**Comment by simonw** [comment]
Hopefully this will do the trick: https://github.com/simonw/datasette/commit/2bdab66772dca51b0c729b4e1063610cb2edd890

**Comment by simonw** [comment]
It almost worked... but I had to fix the `docker login` command: https://github.com/simonw/datasette/commit/3a46d5e3c4278e74c3694f36995ea134bff800bc

Hopefully the next release will be published correctly.

**Comment by jaywgraves** [comment]
I'm using the docker image (0.23.2) and notice some differences/bugs between the docs and the published version with canned queries.  (submitted a tiny doc fix also)

I was able to build the docker container locally using `master` and I'm using that for now.
Would it be possible to manually push 0.24 to DockerHub until the TravisCI stuff is fixed?

I would like to run this in our Kubernetes cluster but don't want to publish a version in our internal registry if I don't have to.
Thanks!

**Comment by simonw** [comment]
The new 0.25 release has been successfully pushed to Docker Hub! https://hub.docker.com/r/datasetteproject/datasette/tags/

One catch: it looks like it didn't update the "latest" tag to point at it. Looking into that now.

**Comment by jaywgraves** [comment]
That works for me.  Was able to pull the public image and no errors on my canned query.  (although a small rendering bug.  I'll create an issue and if I have time today, a PR to fix)
Thanks for the quick response!

**Comment by simonw** [comment]
This works now! The `0.25.1` release was the first release which successfully pushed to Docker Hub: https://hub.docker.com/r/datasetteproject/datasette/tags/

![2018-11-04 at 10 53 pm](https://user-images.githubusercontent.com/9599/47982395-70593700-e084-11e8-8870-9100677c2bde.png)
