### ISSUE TITLE
Limit text display in cells containing large amounts of text

### ISSUE THREAD

**Issue by psychemedia** [simonw/datasette#330]
The default preview of a database shows all columns (is the row count limited?) which is fine in many cases but can take a long time to load / offer a large overhead if the table is a SpatiaLite table containing geometry columns that include large shapefiles.

Would it make sense to have a setting that can limit the amount of text displayed in any given cell in the table preview, or (less useful?) suppress (with notification) the display of overlong columns unless enabled by the user?

An issue then arises if a user does want to see all the text in a cell:

  1) for a particular cell;
  2) for every cell in the table;
  3) for all cells in a particular column or columns

(I haven't checked but what if a column contains e.g. raw image data? Does this display as raw data? Or can this be rendered in a context aware way as an image preview? I guess a custom template would be one way to do that?)

**Comment by simonw** [comment]
This relates to #276 - I'm definitely convinced now that displaying a giant `b'...'` blob on the page is not a useful default.

**Comment by simonw** [comment]
I think this makes sense for the HTML view (not for JSON or CSV). It could be controlled be a new [config option](http://datasette.readthedocs.io/en/latest/config.html), `truncate_html_cells` - which is on by default but can be turned off.

**Comment by simonw** [comment]
```
datasette publish now timezones.db --spatialite \
  --extra-options="--config truncate_cells_html:200" \
  --name=datasette-issue-330-demo \
  --branch=master
```
https://datasette-issue-330-demo-sbelwxttfn.now.sh/timezones-3cb9f64/timezones

![2018-07-10 at 10 39 am](https://user-images.githubusercontent.com/9599/42527428-7eabc6c8-842d-11e8-91ac-5666dbc5872c.png)

But https://datasette-issue-330-demo-sbelwxttfn.now.sh/timezones-3cb9f64/timezones/1 displays the full blob.

**Comment by simonw** [comment]
Documentation: http://datasette.readthedocs.io/en/latest/config.html#truncate-cells-html
