### ISSUE TITLE
extra_options not passed to heroku publisher

### ISSUE THREAD

**Issue by kamicut** [simonw/datasette#334]
I might be wrong but I was not able to publish to `heroku` with `--extra-options`, I think `extra_options` is not being used in this function [here](https://github.com/simonw/datasette/blob/master/datasette/utils.py#L369). 

Any help appreciated!

**Comment by simonw** [comment]
Yup that's definitely a bug.

**Comment by simonw** [comment]
Tested with `datasette publish heroku fixtures.db --extra-options="--config sql_time_limit_ms:4000"`

https://blooming-anchorage-31561.herokuapp.com/-/config
