### ISSUE TITLE
Expose SANIC_RESPONSE_TIMEOUT config option in a sensible way

### ISSUE THREAD

**Issue by bsilverm** [simonw/datasette#339]
Is it possible to configure the sql_time_limit_ms beyond 60 seconds?  It seems queries are still timing out at 60 seconds when sql_time_limit_ms is set to 180000.  We have a very large data set and often encounter timeouts when testing new queries from the datasette UI.  We are optimizing our database as much as we can, but still may require more than 60 seconds for complex queries.

**Comment by simonw** [comment]
It sounds like you're running into the Sanic default response timeout value of 60 seconds: https://github.com/channelcat/sanic/blob/master/docs/sanic/config.md#builtin-configuration-values

For the moment you can over-ride that using an environment variable like this:

    SANIC_RESPONSE_TIMEOUT=6000 datasette fivethirtyeight.db -p 8008 --config sql_time_limit_ms:600000

**Comment by simonw** [comment]
I'm going to turn this into an issue about better supporting the above option.

**Comment by bsilverm** [comment]
Thanks for the quick reply.  Looks like that is working well.

**Comment by simonw** [comment]
Closing this as obsolete since Datasette no longer uses Sanic.
