### ISSUE TITLE
datasette publish cloudrun plugin

### ISSUE THREAD

**Issue by rprimet** [simonw/datasette#400]
Google announced that they may launch a simple service for running Docker containers (previously serverless containers, now called "cloud run" -- link to alpha [here](https://services.google.com/fb/forms/serverlesscontainers/)). If/when this happens, it might be a good fit for publishing datasettes? (at least using the current version, manually publishing a datasette seems relatively painless).

**Comment by simonw** [comment]
I'm really excited about this - it looks like it could be a great plugin.
