### ISSUE TITLE
How to pass configuration to plugins?

### ISSUE THREAD

**Issue by dazzag24** [simonw/datasette#401]
Hi,
Firstly, thanks for your work on datasette, it is a hugely useful tool!

I've been working on a fork [https://github.com/dazzag24/datasette-cluster-map] of datasette-cluster-map to allow the tileserver to be easily switched. Primarily because the tiles being served in the current version use localised text for labels and I'd like to have English used for these names instead.

It uses http://leaflet-extras.github.io/leaflet-providers/preview/ to allow you to simply set the tile provider using a call like so:
```    
let tiles = L.tileLayer.provider('Esri.WorldTopoMap');
```
instead of the current:
```
let tiles = L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        maxZoom: 19,
        detectRetina: true,
        attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
    }),
  ```
However I've got stuck in trying to work out how to pass the provider string to the plugin.
In the documentation: https://datasette.readthedocs.io/en/stable/plugins.html you discuss configuration of plugins and use an example of passing in which latitude and longitude columns should be used.  However I cannot seem to see anywhere in the current datasette-cluster-map code where these config params are passed in or used.

Can you please point me to an example or how to pass configuration from the metadata.json down into a plugin.  Once I've over come this issue I was wondering if you would be interested in taking this change into your version?

Many thanks
Darren

**Comment by simonw** [comment]
Datasette-cluster-map doesn't use the new plugin configuration mechanism yet - it really should!

The best example of how to use this mechanism right now is embedded in the Datasette unit tests: 

https://github.com/simonw/datasette/blob/b7257a21bf3dfa7353980f343c83a616da44daa7/tests/fixtures.py#L266-L270

https://github.com/simonw/datasette/blob/b7257a21bf3dfa7353980f343c83a616da44daa7/tests/test_plugins.py#L139-L145

**Comment by simonw** [comment]
I've released a new version of the datasette-cluster-map plugin to illustrate how plugin configuration can work: https://github.com/simonw/datasette-cluster-map/commit/fcc86c450e3df3e6b81c41f31df458923181527a

**Comment by dazzag24** [comment]
Thanks.  I'll take a look at your changes.
I must admit I was struggling to see how to pass info from the python code in __init__.py into the javascript document.addEventListener function.
