### ISSUE TITLE
How does persistence work?

### ISSUE THREAD

**Issue by ccorcos** [simonw/datasette#403]
I was under the impression that now.sh is for stateless microservices. So where are these SQLite databases stored and when do they get created and destroyed?

**Comment by simonw** [comment]
I talk about that a bit here: https://simonwillison.net/2018/Oct/4/datasette-ideas/#Bundling_the_data_with_the_code

One of the key ideas behind Datasette is that if your data is read-only you can package it up with the rest of your code - so the normal limitations that apply with hosting services like now.sh no longer prevent you from including a database. The SQLite database is just another static binary file that gets packaged up as part of your deployment.

**Comment by ccorcos** [comment]
Ah. That makes much more sense. Interesting approach.
