### ISSUE TITLE
Zeit API v1 does not work for new users - need to migrate to v2

### ISSUE THREAD

**Issue by michaelmcandrew** [simonw/datasette#409]
Hello there,

This looks like a great tool. Thanks. 

Unfortunately, I hit the following error:

```
michael@hazel ~/src/cc-datasette/data/out datasette publish now cc-datasette.db
> WARN! You are using an old version of the Now Platform. More: https://zeit.co/docs/v1-upgrade
> Deploying /tmp/tmpjtrxwsyf/datasette under michaelmcandrew
> Using project datasette
> Error! You tried to create a Now 1.0 deployment. Please use Now 2.0 instead: https://zeit.co/upgrade
```
I'm guessing you might not hit this because you are not a 'new user' of Zeit (https://github.com/zeit/now-cli/issues/1805#issuecomment-452470953).

Would it be a lot of work to upgrade to the new Zeit API, do you think?

**Comment by Uninen** [comment]
It seems this affects the Datasette Publish -page as well: https://github.com/simonw/datasette-publish-support/issues/3

**Comment by michaelmcandrew** [comment]
also linking this zeit issue in case it is helpful: https://github.com/zeit/now-examples/issues/163#issuecomment-440125769

**Comment by simonw** [comment]
Closing this in favour of #717.
