### ISSUE TITLE
How to setup a multi database environment?

### ISSUE THREAD

**Issue by aborruso** [simonw/datasette#410]
Hi,
first of all I need to write that Simon Willison and datasette are really great.

I have probably a stupid question, but it seems to me that I do not have the reply in the documentation.

I have installed datasette and run it with `datasette mydb.db`, and I can reach it  on `http://127.0.0.1:8001`.

But how to work with more than one db? Imagine I have ten sqlite databases, and that I need to explore/query these via datasette, how to run datasette? Is it possibile to create a sort of db index and than run `datasette serve myindex`?

Thank you

**Comment by simonw** [comment]
You can pass multiple databases as command-line arguments, and each one will be loaded. For example:

    datasette mydb.db otherdb.db

Then the URLs should be:

http://127.0.0.1:8001/mydb for the first one
http://127.0.0.1:8001/otherdb for the second one
