### ISSUE TITLE
How to pass named parameter into spatialite MakePoint() function

### ISSUE THREAD

**Issue by dazzag24** [simonw/datasette#411]
Hi,
datasette version: "0.26.2"
extensions: 
       spatialite: "4.4.0-RC0"
sqlite version: "3.22.0"

I have a table of airports with latitude and longitude columns.  I've added spatialite (with KNN support).  After creating the db using csvs-to-sqlit, I run these commands to setup the spatialite tables:

```
conn.execute('SELECT InitSpatialMetadata(1)')

conn.execute("SELECT AddGeometryColumn('airports', 'point_geom', 4326, 'POINT', 2);")

conn.execute('''UPDATE airports SET point_geom = GeomFromText('POINT('||"longitude"||' '||"latitude"||')',4326);''')

conn.execute("SELECT CreateSpatialIndex('airports', 'point_geom');")
```

I'm attempting to create a canned query and have this in my metadata.json file:
```
"find_airports_nearest_to_point":{
    "sql":"SELECT a.pos AS rank, b.id, b.name, b.country, b.latitude AS latitude, b.longitude AS longitude, a.distance / 1000.0 AS dist_km FROM KNN AS a JOIN airports AS b ON (b.rowid = a.fid) WHERE f_table_name = \"airports\" AND ref_geometry = MakePoint( :Long , :Lat ) AND max_items = 10;"}
```
which doesn't seem to perform the templating of the name parameters correctly and I get no results.  

Have also tired:
```
MakePoint( || :Long || , || :Lat || )
```
which returns this error:
```
near "||": syntax error
```

However I cannot seem to find the correct combination of named parameter syntax (:Lat) or sqlite concatenation operator to make it work.  Any ideas if using named parameters inside functions is supported?

Thanks
Darren

**Comment by simonw** [comment]
Have you tried this?

    MakePoint(:Long || ", " || :Lat)

**Comment by dazzag24** [comment]
Hi,
Apologies for the long delay.

I tried your suggesting escaping approach:
`SELECT a.pos AS rank, b.id, b.name, b.country, b.latitude AS latitude, b.longitude AS longitude, a.distance / 1000.0 AS dist_km FROM KNN AS a LEFT JOIN airports AS b ON (b.rowid = a.fid)WHERE f_table_name = 'airports' AND ref_geometry = MakePoint(:Long || ", " || :Lat) AND max_items = 6;
`
and it returns this error:
`wrong number of arguments to function MakePoint()`

Anything else you suggest I try?
Thanks

**Comment by hcarter333** [comment]
Using the [Counties example](https://us-counties.datasette.io/counties/county_for_latitude_longitude?longitude=-122&latitude=37), I was able to pull out the MakePoint method as 

MakePoint(cast(rm_rnb_history_pres.rx_lng as float), cast(rm_rnb_history_pres.rx_lat as float)) as geometry

which worked, giving me a geometry column.

![image](https://github.com/simonw/datasette/assets/363004/6393b712-9e3d-416d-ba37-202934d5f604)


gave

![image](https://github.com/simonw/datasette/assets/363004/219db7b2-8107-41b3-a049-ef4d6bd7ac7a)

I believe it's the cast to float that does the trick. Prior to using the cast, I also received a 'wrong number of arguments' eror.
