### ISSUE TITLE
400 Error when trying to register new user via https://publish.datasettes.com/

### ISSUE THREAD

**Issue by nniiicc** [simonw/datasette#436]
Behavior: When registering a new user via Zeit - confirmation is sent and screen acknowledges registered user... When clicking grant access the next screen is a white 400 error message. 

Replicated: Chrome and Firefox; 2 different email accounts

**Comment by simonw** [comment]
Sadly `publish.datasettes.com` was broken by changes to Zeit, and I don't think I'll be bringing it back.
