### ISSUE TITLE
Plugins are loaded when running pytest

### ISSUE THREAD

**Issue by russss** [simonw/datasette#438]
If I have a datasette plugin installed on my system, its hooks are called when running the main datasette tests. This is probably undesirable, especially with the inspect hook in #437, as the plugin may rely on inspected state that the tests don't know about.

**Comment by simonw** [comment]
Yeah this is a good call. Having pytest set some kind of flag (maybe an environment variable?) that disables auto-plugin discovery is a very reasonable fix here.

**Comment by simonw** [comment]
https://docs.pytest.org/en/latest/example/simple.html#detect-if-running-from-within-a-pytest-run
