### ISSUE TITLE
Define mechanism for plugins to return structured data

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#446]
Several plugin hooks now expect plugins to return data in a specific shape -  notably the new output format hook and the custom facet hook.

These use Python dictionaries right now but that's quite error prone: it would be good to have a mechanism that supported a more structured format.

Full list of current hooks is here: https://datasette.readthedocs.io/en/latest/plugins.html#plugin-hooks

**Comment by simonw** [comment]
I looked at using namedtuples for this but hey have one major constraint: there isn't a clean way to convert them to dictionary-style JSON: https://bugs.python.org/issue30343

So something that uses a class which knows how to be rendered as JSON would be a better fit.

**Comment by simonw** [comment]
Potential design:

```
from collections import OrderedDict


class DataSpec:
    __slots__ = []

    def __init__(self, **kwargs):
        if list(kwargs.keys()) != self.__slots__:
            raise TypeError(
                "{}() has required arguments {} (got {})".format(
                    self.__class__.__name__, self.__slots__, list(kwargs.keys())
                )
            )
        for key in self.__slots__:
            setattr(self, key, kwargs[key])

    def __repr__(self):
        return "<{} {}>".format(self.__class__.__name__, dict(self.as_dict()))

    def as_dict(self):
        return OrderedDict([(key, getattr(self, key)) for key in self.__slots__])


class Output(DataSpec):
    __slots__ = ["body", "content_type", "status_code"]
```

**Comment by simonw** [comment]
The `register_output_renderer()` hook currently returns a dictionary with `body`, `content_type` and `status_code` keys but each of these keys are optionaly. I'm tempted to make all three required to fit this model - @russss any objections?

**Comment by russss** [comment]
In this particular case I don't think there's an issue making all those required. However, I suspect we might have to allow optional values at some point - my preferred solution to russss/datasette-geo#2 would need one.

**Comment by russss** [comment]
Also I have a slight preference against (ab)using `__slots__` to enforce fields, although I have done it myself in the past. It would be possible to do this with __setattr__ instead, although that's an implementation detail and I'm not too fussed about it.

**Comment by simonw** [comment]
So the Python 3.7 way to do this would be dataclasses, but I still want to support 3.5.

This excellent essay has made me think attrs might be the way to go: https://www.revsys.com/tidbits/dataclasses-and-attrs-when-and-why/

**Comment by simonw** [comment]
I've decided not to bother with this, especially having redesigned some hooks to return Datasette standard `Response` objects.
