### ISSUE TITLE
Rename metadata.json to config.json

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#493]
It is increasingly being useful configuration options, when it started out as purely metadata.

Could cause confusion with the `--config` mechanism though - maybe that should be called "settings" instead?

**Comment by simonw** [comment]
This is particularly relevant as plugins increasingly use `metadata.json` for their plugin configuration: https://datasette.readthedocs.io/en/0.32/plugins.html#plugin-configuration

**Comment by simonw** [comment]
I'm definitely doing this rename, now that `metadata.json` is used for `allow` permissions configuration as well as-of #811.

**Comment by simonw** [comment]
I'll also rename `--config` to `--setting`.

**Comment by jefftriplett** [comment]
I was confused by `--config` and I tried passing the json from datasette-ripgrep into `config.json` just as a wild guess. 

A short term solution might be pointing out in plugins that their snippet json can go in `metadata.json` at least makes it easier to search for config options or to know where to start if someone is new.

**Comment by simonw** [comment]
Is there any reason to keep `--setting` rather than moving those items into a `configure.json` file with all the configuration options that currently live in `metadata.json`?

**Comment by jefftriplett** [comment]
I can't keep up with the renaming contexts, but I like having the ability to run datasette+ datasette-ripgrep against different configs: 

```shell
datasette serve --metadata=./metadata.json
```

I have one for all of my code and one per client who has lots of code. So as long as I can point to datasette to something, it's easy to work with.

**Comment by simonw** [comment]
It's going to be called `datasette.json` and the concept of metadata will be split out separately. See:

- #2149
