### ISSUE TITLE
Option to display binary data

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#506]
In #442 we suppressed rendering of binary data:

<img width="358" alt="many-photos-tables__RKAlbumVersion_albumId_RidIndex__36_rows" src="https://user-images.githubusercontent.com/9599/59153367-865d1a80-8a0c-11e9-9384-27dcba0b61b6.png">

It turns out there is one use-case where displaying binary data is useful: when you're poking around looking at random SQLite databases you find in `~/Library` trying to figure out what they are for.

So, a mechanism for opting in to ugly display of binary data again would be useful.

**Comment by simonw** [comment]
This could also be handled by a plugin.

**Comment by simonw** [comment]
Possible plugin direction:

```python
import filetype # https://pypi.org/project/filetype/

@hookimpl(trylast=True)
def render_cell(value):
    if isinstance(value, bytes):
        info = repr(value)
        # May still want to truncate this on table view (but not on row page)
        guess = filetype.guess(value)
        if guess is not None:
            # Need jinja2 markup here for \n to display
            info = "Guess: mime={}, extension={}\n\n{}".format(
                guess.mime, guess.extension, info
            )
        return info

    return None
```

**Comment by simonw** [comment]
What are some other interesting tricks we can use to make binary data a bit more interesting to look at?

https://martin.varela.fi/2017/09/09/simple-binary-data-visualization/ has some really clever visualization tricks - probably a bit much for this plugin though. See also https://codisec.com/binary-visualization-explained/ 

https://github.com/tryexceptpass/perceptio is some much simpler code for rendering an image for a binary.

**Comment by simonw** [comment]
Another cheap trick is the equivalent of the Unix `strings` command - https://stackoverflow.com/questions/6804582/extract-strings-from-a-binary-file-in-python

**Comment by simonw** [comment]
This is quite nice:

```$ od -c /tmp/Thumb64Segment_11.data | head -n 10
0000000   \0  \0   @  \0  \0  \0 005   5   X   T   S   F  \0  \0  \0 001
0000020   \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0
*
0010000  025 030   . 377 026 032   . 377 027 033   - 377 031 035   0 377
0010020  032 036   1 377 036       5 377 037   !   8 377 036   "   : 377
0010040  036       8 377       $   : 377   !   &   ; 377   $   *   ? 377
0010060    '   -   ? 377   %   *   < 377   %   ,   > 377   -   3   E 377
0010100    6   ;   M 377   :   @   O 377   =   C   R 377   @   G   V 377
0010120    @   I   X 377   <   B   Q 377   8   @   N 377   8   @   P 377
0010140    :   C   T 377   ;   C   U 377   :   C   V 377   9   C   W 377
```

**Comment by simonw** [comment]
![3C9CCDBA-F346-47CB-BFEC-964B0426E728](https://user-images.githubusercontent.com/9599/59160835-789ca900-8a8f-11e9-9767-0f50890d17fe.jpeg)

New idea: show essentially this but differentiate the escape sequences in some way. Maybe wrap them in `<code>` or put the non-escape sequences in bold?

**Comment by simonw** [comment]
I'm going to call this `datasette-render-binary`

**Comment by simonw** [comment]
Shipped 0.1 of the plugin! I'm pretty happy with this display format:

<img width="543" alt="many-photos-tables__RKFaceCrop__58_rows" src="https://user-images.githubusercontent.com/9599/59161307-011e4800-8a96-11e9-9768-a168320d8979.png">

**Comment by Gagravarr** [comment]
If you don't mind calling out to Java, then Apache Tika is able to tell you what a load of "binary stuff" is, plus render it to XHTML where possible.

There's a python wrapper around the Apache Tika server, but for a more typical datasette usecase you'd probably just want to grab the Tika CLI jar, and call it with `--detect` and/or `--xhtml` to process the unknown binary blob

**Comment by simonw** [comment]
Calling out to Tika does make me a little nervous, but that's why Datasette has plugins! A plugin that calls Tika (and caches the results) could be really interesting.
