### ISSUE TITLE
Is it possible to publish to Heroku despite slug size being  too large?

### ISSUE THREAD

**Issue by chrismp** [simonw/datasette#513]
I'm trying to push more than 1.5GB worth of SQLite databases -- 535MB compressed -- to Heroku but I get this error when I run the `datasette publish heroku` command.

    Compiled slug size: 535.5M is too large (max is 500M).

Can I publish the databases and make datasette work on Heroku despite the large slug size?

**Comment by simonw** [comment]
Unfortunately not - I really wish this was possible. I have not yet found a great serverless solution for publishing 1GB+ databases - they're too big for Heroku, Cloud Run OR Zeit Now. Once databases get that big the only option I've found is to run a VPS (or an EC2 instance) with a mounted hard drive volume and execute `datasette serve` on that instance, with an nginx running on port 80 that proxies traffic back to Datasette.

I'd love to figure out a way to make hosting larger databases as easy as it currently is to host small ones.

**Comment by chrismp** [comment]
Ah, so basically put the SQLite databases on Linode, for example, and run `datasette serve` on there? I'm comfortable with that.
