### ISSUE TITLE
Show total/unfiltered row count when filtering

### ISSUE THREAD

**Issue by rixx** [simonw/datasette#523]
When I'm seeing a filtered view of a table, I'd like to be able to see something like '2 rows where status != "closed" (of 1000 total)' to have a context for the data I'm seeing – e.g. currently my database is being filled by an importer, so this information would be super helpful.

Since this information would be a performance hit, maybe something like '12 rows where status != "closed" (of ??? total)' with lazy-loading on-click(?) could be applied (Or via a "How many total?" tooltip, or …)

**Comment by simonw** [comment]
For databases opened in immutable mode we pre-calculate the total row count for every table precisely so we can offer this kind of functionality without too much of a performance hit. The total row count is already available to the template (you can hit the .json endpoint to see it), so implementing this should be possible just by updating the template.

For mutable databases we have a mechanism for attempting the count and giving up after a specified time limit - we can use that to get "3 of many".

It looks like this is actually a dupe of #127 and #134.

**Comment by rixx** [comment]
Ah, apologies – I had found and read those issues, but I was under the impression that they refered only to the filtered row count, not the unfiltered total row count.
