### ISSUE TITLE
Unable to use rank when fts-table generated with csvs-to-sqlite

### ISSUE THREAD

**Issue by clausjuhl** [simonw/datasette#527]
Hi Simon.

If i generate a fts-table with the csvs-to-sqlite f-option, I'm unable to use (in datasette's GUI) the internal ranking of the table for sorting or viewing, but if I generate the fts-table with the enable-fts argument from sqlite-utils, everyrthing works ok. Eg.:

datasette, version 0.28
sqlite-utils, version 1.2.1
csvs-to-sqlite, version 0.9

No column named rank with these commands:
$ csvs-to-sqlite minutes.csv minutes.db -f text_data
$ datasette -i minutes.db
select rank, * from minutes_fts where minutes_fts match 'dog'

Everything ok with these commands:
$ csvs-to-sqlite minutes.csv minutes.db
$ sqlite-utils enable-fts minutes.db text_data
$ datasette -i minutes.db
select rank, * from minutes_fts where minutes_fts match 'dog'

Am I doing something wrong?

Thank you for a great application!

**Comment by simonw** [comment]
The `select rank, *` feature is only available with FTS5 - it won't work with FTS4. So my best guess is that `csvs-to-sqlite` is setting up FTS with FTS4 when you want FTS5.

... I tested on my own machine and that is indeed what's happening! And in fact it looks like it's a known bug - I should fix that! https://github.com/simonw/csvs-to-sqlite/issues/41

**Comment by simonw** [comment]
Closing in favour of that bug in the csvs-to-sqlite repo.

**Comment by simonw** [comment]
I just released csvs-to-sqlite 0.9.1 with this bug fix: https://github.com/simonw/csvs-to-sqlite/releases/tag/0.9.1
