### ISSUE TITLE
Conflict between datasette and uvicorn click versions

### ISSUE THREAD

**Issue by jonheslop** [simonw/datasette#565]
Hello Datasette is awesome thanks so much!

I not very familiar with Python but I think there is a problem with datasette docker builds 

I keep getting this error

```
ERROR: uvicorn 0.8.4 has requirement click==7.*, but you'll have click 6.0 which is incompatible.
ERROR: datasette 0.29.2 has requirement click~=7.0, but you'll have click 6.0 which is incompatible.
```

The full log from the docker build is here - https://gist.github.com/jonheslop/e01cd322e761cfaf34f0cb83f86411b0

Just in case it’s helpful this is my setup - https://github.com/dotwatcher/dotwatcher-data

**Comment by simonw** [comment]
Today Datasette uses `"click~=7.1.1"` and Uvicorn uses `"click==7.*"` so I think we are OK.
