### ISSUE TITLE
Datasette Edit

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#567]
Datasette started out immutable. Then it gained the ability to run against read-only databases that were being modified by other processes. It's time for the next logical progression: the option to allow Datasette (or more likely individual plugins) to write to the database!

This is going to require some careful rethinking of how connection management works.

**Comment by clausjuhl** [comment]
Hi Simon. Is there somewhere to read about its ability to run against read-only databases that are able to be modified by other processes? While we're waiting for "Datasette Edit" :)

**Comment by simonw** [comment]
@clausjuhl I wrote a bit about that here: https://simonwillison.net/2019/May/19/datasette-0-28/

Short version: just point Datasette at a SQLite file and update it from another process - it should work fine! I do it all the time now - I'll have a script running that writes to a database and I'll use Datasette to monitor progress.

**Comment by simonw** [comment]
Closing this in favour of #682 - a mechanism for writing to databases from a clue which is being developed in pull request #683.
