### ISSUE TITLE
Ship a Docker image of the whole thing

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#57]
The generated Docker images can then just inherit from that. This will speed up deploys as no need to `pip install` anything.

- [ ] Ship that image to Docker Hub
- [ ] Update the generated Dockerfile to use it

**Comment by macropin** [comment]
I'm happy to contribute this. Just let me know if you want a Dockerfile for development or production purposes, or both. 

If it's prod then we can just pip install the source from pypi, otherwise for dev we'll need a `requirements.txt` to speed up rebuilds.

**Comment by macropin** [comment]
Let me know if you'd like a PR. The image is usable as 
`docker run --rm -t -i -p 9000:8001 -v $(pwd)/db:/db datasette datasette serve /db/chinook.db`

**Comment by simonw** [comment]
I’m intrigued by this pattern: 

https://github.com/macropin/datasette/commit/147195c2fdfa2b984d8f9fc1c6cab6634970a056#diff-3254677a7917c6c01f55212f86c57fbfR8

What’s the benefit of doing that? Does it result in a smaller image size?

**Comment by macropin** [comment]
The pattern is called "multi-stage builds". And the result is a svelte 226MB image (201MB for 3.6-slim) vs 700MB+ for the full image.

**Comment by simonw** [comment]
Thanks for the explanation! Please do start a pull request.

**Comment by simonw** [comment]
Shipped to Docker Hub: https://hub.docker.com/r/datasetteproject/datasette/

I did this manually the first time. I'll set Travis up to do this automatically in #329
