### ISSUE TITLE
Exposing Datasette via  Jupyter-server-proxy

### ISSUE THREAD

**Issue by psychemedia** [simonw/datasette#573]
It is possible to expose a running `datasette` service in a Jupyter environment such as a MyBinder environment using the [`jupyter-server-proxy`](https://github.com/jupyterhub/jupyter-server-proxy).

For example, using [this demo Binder](https://mybinder.org/v2/gh/binder-examples/r/master?filepath=index.ipynb) which has the server proxy installed, we can then upload a simple test database from the notebook homepage, from a Jupyter termianl install datasette and set it running against the test db on eg port 8001 and then view it via the path `proxy/8001`.

Clicking links results in 404s though because  the `datasette` links aren't relative to the current path?

![image](https://user-images.githubusercontent.com/82988/64689964-44b69280-d487-11e9-8f9f-3681422bcc9f.png)

**Comment by psychemedia** [comment]
In passing, it looks like a start was made on a datasette Jupyter server extension in https://github.com/lucasdurand/jupyter-datasette although the build fails in MyBinder.

**Comment by wragge** [comment]
Did you manage to find an answer to this? I've got a notebook to help people generate datasets on the fly from an API, so it would be cool if they flick it to Datasette for initial exploration.

**Comment by psychemedia** [comment]
Fixed by @simonw; example here: https://github.com/simonw/jupyterserverproxy-datasette-demo
