### ISSUE TITLE
Improve usage description of --host option

### ISSUE THREAD

**Issue by terrycojones** [simonw/datasette#574]
It would be nice if the `--host` option had a clearer description. I tried to get datasette running on an AWS instance and it took a while to realize it was only listening on localhost. So I wanted to make it listen on an non-localhost interface and tried giving a couple of values to `--host` (a host name, then an interface name), but none of them did. In the end I read the source to see that the option is passed to `uvicorn` and looked at the uvicorn docs, which also didn't help. Then I searched the web for "example running datasette on a host" which led me to https://github.com/simonw/datasette/issues/514 where I saw someone using `-h 0.0.0.0`. I tried that and it works.  That usage could be mentioned somewhere, and might save someone else some time.

**Comment by simonw** [comment]
That's a great idea, thanks for the feedback.

**Comment by simonw** [comment]
New description:
```
  -h, --host TEXT           Host for server. Defaults to 127.0.0.1 which means
                            only connections from the local machine will be
                            allowed. Use 0.0.0.0 to listen to all IPs and
                            allow access from other machines.
```
