### ISSUE TITLE
Databases on index page should display in order they were passed to "datasette serve"?

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#585]
If you run this:

    datasette serve -h 127.0.0.1 -p 8000 -m phone-locations.db healthkit.db locations.db genome.db

Then the index page for that Datasette instance should show the databases in the order they were specified on the command-line.

Mind you when we add pagination to that page in #468 we may want to do something different here.

**Comment by rixx** [comment]
I think this would be good, yeah – currently, databases are explicitly sorted by name in the IndexView, we could just remove that part (and use an `OrderedDict` for consistency, I suppose)?
