### ISSUE TITLE
Queries per DB table in metadata.json

### ISSUE THREAD

**Issue by bsilverm** [simonw/datasette#588]
It doesn't appear possible to have separate queries defined per database table.  When I do something like below, my table descriptions show up but not the queries:

` "databases": {
      "MYDB": {
        "tables": {
          "MYFIRSTTABLE": {
            "source": "Test",
            "source_url": "https://www.google.com",
            "queries": {
                "Query 1": {
                    "sql": "select * from MYFIRSTTABLE",
                    "title": "Query 1",
                    "description": "This is the first query"
                  },
            }
          },
          "MYSECONDTABLE": {
              "source":"Test2",
              "source_url":"https://www.google.com",
            "queries": {
                "Query 2" : {
                    "sql":"select * from MYSECONDTABLE;",
                    "title": "Query 2",
                    "description":"This is the second query"
                }
            }
          }
        }`

**Comment by simonw** [comment]
I think I see what's gone wrong here. Here's your example re-indented:
```json
{
    "databases": {
        "MYDB": {
            "tables": {
                "MYFIRSTTABLE": {
                    "source": "Test",
                    "source_url": "https://www.google.com",
                    "queries": {
                        "Query 1": {
                            "sql": "select * from MYFIRSTTABLE",
                            "title": "Query 1",
                            "description": "This is the first query"
                        }
                    }
                },
                "MYSECONDTABLE": {
                    "source": "Test2",
                    "source_url": "https://www.google.com",
                    "queries": {
                        "Query 2": {
                            "sql": "select * from MYSECONDTABLE;",
                            "title": "Query 2",
                            "description": "This is the second query"
                        }
                    }
                }
            }
        }
    }
}
```

The `"queries" section isn't supported at the table level - it only works at the database level. So that example should look like this:

```json
{
    "databases": {
        "MYDB": {
            "tables": {
                "MYFIRSTTABLE": {
                    "source": "Test",
                    "source_url": "https://www.google.com"
                },
                "MYSECONDTABLE": {
                    "source": "Test2",
                    "source_url": "https://www.google.com"
                }
            },
            "queries": {
                "Query 1": {
                    "sql": "select * from MYFIRSTTABLE",
                    "title": "Query 1",
                    "description": "This is the first query"
                },
                "Query 2": {
                    "sql": "select * from MYSECONDTABLE;",
                    "title": "Query 2",
                    "description": "This is the second query"
                }
            }
        }
    }
}
```

**Comment by simonw** [comment]
Closing this, but #260 would definitely help here.

**Comment by bsilverm** [comment]
Thanks for the reply.  I was hoping queries per table were supported, as I have an application that builds tables depending on the user input to the application.  It will either create one table, or two.. and if one or the other is missing, certain queries will return errors.  Of course I can work around this by labeling the query name and hope users don't click queries they have not created a table for, but ideally the user would see the queries available based on the tables that exist in their database.
