### ISSUE TITLE
upgrade to uvicorn-0.9 to be Python-3.8 friendly

### ISSUE THREAD

**Issue by stonebig** [simonw/datasette#594]
uvicorn-0.8 relies on websockets-0.7  which lacks python-3.8 compatiblity

**Comment by willingc** [comment]
Just an FYI for folks wishing to run datasette with Python 3.8, I was able to successfully use datasette with the following in a virtual environment:

```
pip install uvloop==0.14.0rc1
pip install uvicorn==0.9.1
```

**Comment by simonw** [comment]
#622

**Comment by simonw** [comment]
Closing this in favour of #627 which upgrades to uvicorn 0.10.4
