### ISSUE TITLE
Character encoding bug with CSV export

### ISSUE THREAD

**Issue by JoeGermuska** [simonw/datasette#598]
I was just poking around, and at [this URL](https://sql-murder-mystery.datasette.io/sql-murder-mystery/crime_scene_report.csv?_stream=on&type=arson&_size=max), I encountered this error:

```
'latin-1' codec can't encode character '\u2019' in position 27: ordinal not in range(256)
```

**Comment by simonw** [comment]
This is fixed in master - should be releasing the fix as Datasette 0.30 in the next few days. #584
