### ISSUE TITLE
Datasette FTS detection bug

### ISSUE THREAD

**Issue by null92** [simonw/datasette#616]
I'm having a trouble with datasette. I deployed EXACTLY the same project on two different apps on Heroku. Both have databases (not all) with FTS activated but only one detects and works fine. You can take a look here:
With search: http://teste-templates.herokuapp.com/amazonia_protege/car
Without search: http://bases.vortex.media/amazonia_protege/car
![teste](https://user-images.githubusercontent.com/49656826/68306310-11a80e00-0088-11ea-8d1c-db3bd3375518.jpg)

**Comment by simonw** [comment]
I think I know what's going on here.

http://bases.vortex.media/-/versions says it's running `"version": "0.29.2"` of Datasette.

http://teste-templates.herokuapp.com/-/versions (the one that works) is running `"version": "0.30.2"`

I fixed a bug with FTS detection in 0.29.3 - https://datasette.readthedocs.io/en/stable/changelog.html#v0-29-3 fixed - #570

So upgrading to the latest release should fix this.

**Comment by null92** [comment]
Thank you so much, Simon!

Now, I'm contacting Heroku's support team to find a way to update the Datasette version on bases.vortex.media.

Do you know how to do it?
