### ISSUE TITLE
Provide a cookiecutter template for creating new plugins

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#642]
See this conversation: https://twitter.com/psychemedia/status/1199707352540368896

**Comment by simonw** [comment]
It can include options for quickly bootstrapping custom template function or SAL function plugins, which are really simple.

**Comment by simonw** [comment]
This will also make bundling static files less error-prone.

**Comment by simonw** [comment]
One thing that put me off cookiecutter in the past is that I didn't think it could conditionally create files.

I was wrong! You can use post- hooks to delete the files that you didn't need: https://github.com/audreyr/cookiecutter-pypackage/blob/master/hooks/post_gen_project.py

I could use this mechanism to rename directories too if I needed to.

**Comment by psychemedia** [comment]
Would cookie cutter approaches also work for creating various flavours of customised templates?

I need to try to create a couple of site for myself to get a feel for what sorts of thing are easily doable, and what cribbable cookie cutter items might be. I'm guessing https://simonwillison.net/2019/Nov/25/niche-museums/ is a good place to start from?

**Comment by simonw** [comment]
@psychemedia sorry I missed your comment before.

Niche Museums is definitely the best example of custom templates at the moment: https://github.com/simonw/museums/tree/master/templates

I want to comprehensively document the variables made available to custom templates before shipping Datasette 1.0 - just filed that as #857.

**Comment by simonw** [comment]
Shipped this today! https://github.com/simonw/datasette-plugin is a cookiecutter template for creating new plugins.
