### ISSUE TITLE
Move hashed URL mode out to a plugin

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#647]
They used to be the default until #418. Since making them optional I haven't felt the need to use them even once.

That suggests to me that they should be removed. I think their effect could be entirely handled by an ASGI wrapping plugin.

https://datasette.readthedocs.io/en/0.32/performance.html#hashed-url-mode

**Comment by simonw** [comment]
Now that I'm looking at refactoring how views work in #878 it's clear that the gnarliest, most convoluted code I need to deal with relates to this old feature.

I'm going to remove it entirely. Any performance enhancement or provides can be achieved just as well by using regular URLs and a caching proxy.

I may provide a 404 handling plugin that attempts to rewrite old URLs that used this mechanism, but I won't do any more than that.

**Comment by simonw** [comment]
This needs to take into account the changes made here:
- #1439

In the new encoding scheme, `-` has a special meaning in a table name: https://docs.datasette.io/en/latest/internals.html#dash-encoding

I think `~` is the right character to use to separate a database name from its hash. `~` should be a URL safe character according to Python's implementation of percent-encoding, see comment here:  https://github.com/simonw/datasette/blob/c5791156d92615f25696ba93dae5bb2dcc192c98/datasette/utils/__init__.py#L1146-L1152

So the plugin could check for `dbname~hash` and react based on that.

**Comment by simonw** [comment]
Built a prototype of that plugin:
```python
from datasette import hookimpl
from functools import wraps


@hookimpl
def asgi_wrapper(datasette):
    def wrap_with_hashed_urls(app):
        @wraps(app)
        async def hashed_urls(scope, receive, send):
            # Only triggers on pages with a path not starting in /-/
            # and where the first page component matches a database name
            if scope.get("type") != "http":
                await app(scope, receive, send)
                return
            path = scope["path"].lstrip("/")
            if not path or path.startswith("-/"):
                await app(scope, receive, send)
                return
            potential_database = path.split("/")[0]
            # It may or may not be already dbname~hash
            if "~" in potential_database:
                db_name, hash = potential_database.split("~", 1)
            else:
                db_name = potential_database
                hash = ""
            # Is db_name a database we have a hash for?
            try:
                db = datasette.get_database(db_name)
            except KeyError:
                await app(scope, receive, send)
                return

            if db.hash is not None:
                # TODO: make sure db.hash is documented
                if db.hash[:7] != hash:
                    # Send a redirect
                    path_bits = path.split("/")
                    new_path = "/" + "/".join(["{}-{}".format(db_name, db.hash[:7])] + path_bits[1:])
                    if scope.get("query_string"):
                        new_path += "?" + scope["query_string"].decode("latin-1")

                    await send({
                        "type": "http.response.start",
                        "status": 302,
                        "headers": [
                            [b"location", new_path.encode("latin1")]
                        ],
                    })
                    await send({"type": "http.response.body", "body": b""})
                    return
                else:
                    # Add a far-future cache header
                    async def wrapped_send(event):
                        if event["type"] == "http.response.start":
                            original_headers = event.get("headers") or []
                            event = {
                                "type": event["type"],
                                "status": event["status"],
                                "headers": original_headers + [
                                    [b"Cache-Control", b"max-age=31536000"]
                                ],
                            }
                        await send(event)

                    await app(scope, receive, wrapped_send)
                    return
                
            await app(scope, receive, send)
        return hashed_urls
    return wrap_with_hashed_urls
```
One catch: it doesn't affect the way URLs are generated - so every internal link within Datasette links to the non-hash version and then triggers a 302 redirect to the hashed version.

**Comment by simonw** [comment]
Maybe the plugin should interfere with `datasette.databases` on startup and change the registered name for each one?

**Comment by simonw** [comment]
This seems to do the job:
```python
@hookimpl
def startup(datasette):
    for name, database in datasette.databases.items():
        if database.hash:
            new_name = "{}_{}".format(name, database.hash[:7])
            del datasette.databases[name]
            datasette.databases[new_name] = database
```
Would have to teach the rest of the plugin to split on `_` and to only redirect if the user seems to be hitting the URL for an old hash after which Datasette has been restarted with an updated database.

**Comment by simonw** [comment]
I'm now convinced this is feasible enough that it's worth doing in time for Datasette 1.0.

**Comment by simonw** [comment]
It would be neat if the plugin could spot old-style hash redirect URLs (maybe on 404) and redirect those too.

**Comment by simonw** [comment]
I shipped the first version of this: https://github.com/simonw/datasette-hashed-urls

Next step: test it with a live demo:
- https://github.com/simonw/datasette-hashed-urls/issues/2

**Comment by simonw** [comment]
The plugin works. I'm going to implement one last feature for it:

- https://github.com/simonw/datasette-hashed-urls/issues/3

Then I can remove hashed URL mode in a separate issue.

**Comment by fgregg** [comment]
thank you for continuing to support his feature! should i use this plugin with the current release on pypi?
