### ISSUE TITLE
README information is obscured by feature history

### ISSUE THREAD

**Issue by labstersteve** [simonw/datasette#659]
While it's sometimes valuable to know how a project has developed, there is usually little justification for including this information in the README, and certainly not immediately after other key information such as "what does this package do, and who might want to use it?"

Might I recommend that the feature history is migrated to an Appendix in the documentation?

**Comment by simonw** [comment]
Great feedback, thanks. This is mainly caused by the lack of an official Datasette website! I've been working on that - I'll move the news section out of the readme as soon as it's live.
