### ISSUE TITLE
Exposing a different port that 8001 in `package`

### ISSUE THREAD

**Issue by dvhthomas** [simonw/datasette#661]
I see  how to alter the port using `datasette serve -p XXX` per the docs. However, I'm packaging up to server the container on AppEngine flexible, which [requires](https://cloud.google.com/appengine/docs/flexible/custom-runtimes/build#listening_to_port_8080)  that the container is serving traffic on port 8080.

https://github.com/simonw/datasette/blob/7950105c278b140e6cb665c68b59df219870f9bc/Dockerfile#L41

Is there a way to inject a non-default port into the Dockerfile, or should I just do something like `sed` to replace 8001 with 8080 after `dataset package` has done it's thing? Thanks for the advice.

**Comment by simonw** [comment]
Having `datasette package` take an optional port argument seems like a good feature to me.

**Comment by simonw** [comment]
This has now shipped as part of Datasette 0.34: https://datasette.readthedocs.io/en/stable/changelog.html#v0-34

**Comment by dvhthomas** [comment]
Thanks for the elegant solution to the problem as stated. I'm packaging right now :-)
