### ISSUE TITLE
Cashe-header missing in http-response

### ISSUE THREAD

**Issue by clausjuhl** [simonw/datasette#681]
Hi Simon. I need some help with both understanding and adding http-headers. If I call datasette on localhost with --config default_cache_ttl:120 and --cors, I only get the following response-headers:

access-control-allow-origin: *
content-type: text/html; charset=utf-8
date: Sat, 22 Feb 2020 10:32:15 GMT
referrer-policy: no-referrer
server: uvicorn
transfer-encoding: chunked

Cors works, but no caching-header is set? Same thing happens if I use the command in a Dockerfile and run datasette with docker.

Second, how can one add headers to uvicorn? I've tried to add uvicorn commands to the Dockerfile, before the final datasette command, but it doesn't work. Is there any way to add headers to the uvicorn.run() command i datasette? I particular, I would like to add some of the missing security-headers:

<img width="1010" alt="Screenshot 2020-02-22 at 11 48 03" src="https://user-images.githubusercontent.com/2181410/75091037-5ab59c80-5569-11ea-8dbb-22357f1aa4c8.png">

Thank you for a great product!

**Comment by simonw** [comment]
For adding extra HTTP headers I suggest writing a plugin. There's an example in the docs of one that adds a simple HTTP header here: https://datasette.readthedocs.io/en/stable/plugins.html#asgi-wrapper-datasette

You don't need to bundle it up as a full Python package - you can create a `plugins/add_headers.py` file and run Datasette with `--plugins-dir=plugins/`: https://datasette.readthedocs.io/en/stable/plugins.html#writing-plugins

**Comment by simonw** [comment]
The `default_cache_ttl` config currently only takes effect for databases that are loaded in immutable mode using `-i database.db`: https://datasette.readthedocs.io/en/stable/performance.html#immutable-mode

**Comment by simonw** [comment]
Those security headers from your screenshot are definitely worth me thinking more about. Even if not as core features they could make a great officially supported plugin.

**Comment by clausjuhl** [comment]
Excellent. I'll implement the simple plugin-solution now. And will have a go at a more mature plugin later. Thanks!
