### ISSUE TITLE
Foreign key : case of a link to the associated row not displayed

### ISSUE THREAD

**Issue by JBPressac** [simonw/datasette#726]
Hello,
I use Datasette to publish tsv files linked together by foreign keys declared thanks to sqlite-utils. In one table, [prelib_personne](http://crbc-dataset.huma-num.fr/prelib/prelib_personne), the foreign keys are properly noticed by a link to the associated row (for instance ville_naissance_id is properly linked to prelib_ville). But every link to the foreign key prelib_oeuvre.id fails. For instance, [prelib_ecritoeuvre](http://crbc-dataset.huma-num.fr/prelib/prelib_ecritoeuvre) has links to prelib_personne but none to prelib_oeuvre. In despite of the schema:

CREATE TABLE "prelib_ecritoeuvre" (
"id" INTEGER,
  "fonction_id" INTEGER,
  "oeuvre_id" INTEGER,
  "personne_id" INTEGER
  ,PRIMARY KEY ([id]),
   FOREIGN KEY(fonction_id) REFERENCES prelib_fonctionecritoeuvre(id),
   FOREIGN KEY(personne_id) REFERENCES prelib_personne(id),
   FOREIGN KEY(oeuvre_id) REFERENCES prelib_oeuvre(id)
); 

Would you have any clue to investigate the reason of this problem?
Thanks,

**Comment by simonw** [comment]
Aah - yes I've seen this a few times before in my own projects. The problem is that the column types don't match up - your `oeuvre_id` column here is an integer, but if you look at the schema for `prelib_oeuvre` (at the bottom of this page: http://crbc-dataset.huma-num.fr/prelib/prelib_oeuvre) you'll see that it's defined as text:

```sql
CREATE TABLE "prelib_oeuvre" (
"id" TEXT,
  "titre" TEXT,
  "descriptif" TEXT,
  "wikidata" TEXT,
  "ark_bnf" TEXT,
  "notes" TEXT
  ,PRIMARY KEY ([id])
);
```
