### ISSUE TITLE
Idea: option to automatically configure based on directory layout

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#731]
My Datasette projects increasingly take on the following structure:

- `metadata.json` with the metadata
- One or more `something.db` database files
- A `templates/` folder with some custom templates
- A `plugins/` folder with some custom plugins

Then I have to run Datasette like this:

    datasette *.db -m metadata.json --template-dir=templates --plugins-dir=plugins

It would be really interesting if Datasette had a special mode where you could point it at a directory with the above layout and it would automatically configure itself based on the contents.

Maybe even allow `datasette serve` to detect if it was passed a single argument that's a directory, not a file, and kick in to "directory layout configuration mode" in that case:

    datasette .

**Comment by simonw** [comment]
I started thinking about this while building https://github.com/simonw/datasette-publish-now

The Vercel hosting platform is built on ASGI - so I need a way to provide an `app` ASGI object for it to use rather than Datasette's normal pattern of starting up the server using the `datasette serve` command.

The plugin currently does that by generating an `index.py` file that looks like this:

```python
from datasette.app import Datasette
import json
metadata = dict()
try:
    metadata = json.load(open("metadata.json"))
except Exception:
    pass
app = Datasette([], ["fixtures.db"], metadata=metadata).app()
```
But that means I have to replicate the different CLI options - `--plugins-dir` etc - and figure out how to pass them to the `Datasette()` constructor.

This would be a whole lot easier if I could use `app = Datasette(configure_directory=".")` and provide a magically configured instance based on the presence of files in the specified directory.

**Comment by simonw** [comment]
I linked to this from https://github.com/zeit/now/discussions/4055

**Comment by eyeseast** [comment]
I've almost suggested this same thing a couple times. I tend to have Makefile (because I'm doing other `make` stuff anyway to get data prepped), and I end up putting all those CLI options in something like `make run`. But it would be way easier to just have all those typical options -- plugins, templates, metadata -- be defaults.

**Comment by simonw** [comment]
For `--static` this could work by letting you create the following:

- `static/css/`
- `static/js/`

Which would be automatically mounted at `/js/...` and `/css/...`

Or maybe just mount `static/` at `/static/` instead?

**Comment by eyeseast** [comment]
Mounting `./static` at `/static` seems the simplest way. Saves you the trouble of deciding what else (`img` for example) gets special treatment.

**Comment by simonw** [comment]
Yeah I'll do that. My original thinking on allowing the `--static` option to mount other things to the root is that it would make it easy for people to add HTML "pages" to their site - like https://www.niche-museums.com/map for example.

But I've proposed a better solution for that here: #648

**Comment by simonw** [comment]
I've shipped #648 now, so no reason not to go with the `static/` folder as the thing that gets detected and mounted as `/static`.

**Comment by simonw** [comment]
Work now happening in the pull request: https://github.com/simonw/datasette/issues/731

**Comment by simonw** [comment]
Documentation: https://datasette.readthedocs.io/en/latest/config.html#configuration-directory-mode
