### ISSUE TITLE
strange behavior using accented characters

### ISSUE THREAD

**Issue by aborruso** [simonw/datasette#736]
Hi,
when I search `incompatibilità` [here](https://my-database.now.sh/commissioniComunePalermo/youtube), using full text search, it becomes `incompatibilitÃÂ ` and I have no result.

If I encode the `à` char in the URL (`incompatibilit%C3%A0`) I have the right result.

![image](https://user-images.githubusercontent.com/30607/80275201-00a79380-86e0-11ea-865e-f7e1474e8098.png)

**Comment by simonw** [comment]
I'm suspicious that this might be a bug with `datasette-publish-now` not with core Datasette. See https://github.com/simonw/datasette-publish-now/issues/20 - I think that might be the same issue.

**Comment by simonw** [comment]
Would you mind trying publishing your database using one of the other options - Heroku, Cloud Run or https://fly.io/ - and see if you have the same bug there?

If you DO get the same bug with another option, please re-open this issue.

**Comment by aborruso** [comment]
> Would you mind trying publishing your database using one of the other options - Heroku, Cloud Run or https://fly.io/ - and see if you have the same bug there?

It works in heroku, than might be a bug with datasette-publish-now.

Thank you
