### ISSUE TITLE
Non-utf8 encoding in exceptionhandlers and custom-pages

### ISSUE THREAD

**Issue by clausjuhl** [simonw/datasette#752]
Hi Simon.

Whenever a response is not piped through a router-view, the template is encoded in latin-1 (I think). This is especially a problem (for me) with the new custom_pages-functionality, but also problematic with the 404- and 500-handlers. Thanks!

**Comment by simonw** [comment]
Good catch: it looks like we're not specifying the charset for those pages:
```$ curl -i 'https://latest.datasette.io/404'
HTTP/1.1 404 Not Found
access-control-allow-origin: *
content-type: text/html
Date: Mon, 04 May 2020 16:23:25 GMT
Server: Google Frontend
Content-Length: 605

<!DOCTYPE html>
<html>
<head>
    <title>Error 404</title>
```
