### ISSUE TITLE
Error pages not correctly loading CSS

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#777]
e.g. https://latest.datasette.io/fixtures/compound_three_primary_keys.tsv?_size=max

<img width="856" alt="Error_404_and_All_plugin_hooks_should_have_unit_tests_·_Issue__773_·_simonw_datasette" src="https://user-images.githubusercontent.com/9599/83092786-e5b79e80-a052-11ea-9cd7-6a1c01eb08e7.png">

The HTML starts like this:

```html
<!DOCTYPE html>
<html>
<head>
    <title>Error 404</title>
    <link rel="stylesheet" href="-/static/app.css?">
```

**Comment by thisismyfuckingusername** [comment]
think, because the given URL of the CSS file doesn't have any complete parameters after query 
Try to complete the parameter 
`<link rel="stylesheet" href="-/static/app.css?(whatever you want that shows a css file)">`

**Comment by simonw** [comment]
This is particularly worth fixing now that 403 forbidden pages are much more likely due to #811.

**Comment by simonw** [comment]
Clue: https://latest.datasette.io/404 displays correctly but https://latest.datasette.io/fixtures/404 does not.

**Comment by simonw** [comment]
Here's why:

https://github.com/simonw/datasette/blob/49d6d2f7b0f6cb02e25022e1c9403811f1fa0a7c/datasette/app.py#L1024-L1029

404 errors are rendered by looking for a template from `["404.html", "500.html"]`.

`404.html` doesn't actually ship with Datasette (plugins or custom template directories can provide it). So the `500.html` template is used.

That template extends `base.html`, which expects there to be `base_url` and `app_css_hash` variables. But as you can see in the excerpt above, those variables are not being passed to the template context when the error page is rendered.
