### ISSUE TITLE
base_url doesn't seem to work when adding criteria and clicking "apply"

### ISSUE THREAD

**Issue by tballison** [simonw/datasette#865]
Over on Apache Tika, we're using datasette to allow users to make sense of the metadata for our file regression testing corpus.

This could be user error in how I've set up the reverse proxy!

I started datasette like so:
`docker run -d -p 8001:8001 -v `pwd`:/mnt datasetteproject/datasette datasette -p 8001 -h 0.0.0.0 /mnt/corpora-metadata.db --config sql_time_limit_ms:60000 --config base_url:/datasette/`

I then reverse proxied like so:

  ProxyPreserveHost On
  ProxyPass /datasette http://x.y.z.q:xxxx
  ProxyPassReverse /datasette http://x.y.z.q:xxx

Regular sql works perfectly:
https://corpora.tika.apache.org/datasette/corpora-metadata?sql=select+mime_string%2C+count%281%29+as+cnt%0D%0Afrom+profiles+p%0D%0Ajoin+mimes+m+on+p.mime_id%3Dm.mime_id%0D%0Agroup+by+mime_string%0D%0Aorder+by+cnt+desc

However, adding criteria and clicking 'Apply' 
https://corpora.tika.apache.org/datasette/corpora-metadata/tika_1_24_1_mimes?_sort=file&mime__exact=text%2Fplain

bounces back to:
https://corpora.tika.apache.org/corpora-metadata/tika_1_24_1_mimes?_sort=file&file__contains=bug&mime__exact=text%2Fplain

**Comment by tballison** [comment]
This seems to be a duplicate of: https://github.com/simonw/datasette/issues/838

**Comment by simonw** [comment]
Thanks for the bug report. Yes I think #838 may be the same issue. Will investigate.

**Comment by simonw** [comment]
Had a thought: this is likely to break in plugins too, such as `datasette-edit-schema` which constructs URLs for redirects e.g. here: https://github.com/simonw/datasette-edit-schema/blob/dbd0abee6dd3385b114cfe9671f7ead1c4855b60/datasette_edit_schema/__init__.py#L46-L48

**Comment by simonw** [comment]
Can anyone give me some detailed steps to reproduce for this issue? I think I need to set up my own local nginx or Apache proxy so I can really dig into this and figure out what's going on.

**Comment by simonw** [comment]
Tracking ticket: #1023

**Comment by simonw** [comment]
I managed to recreate proxying using `nginx` in #1024 - but I could not replicate this bug. I did NOT use `ProxyPassReverse` though. I think that may be what caused the problem.

I'll add a section to the documentation about this shortly.

**Comment by simonw** [comment]
It looks like there are places where Datasette might return a redirect that doesn't take `base_url` into account - I'm planning on fixing those here, after which I think `ProxyPassReverse` should no longer be necessary. https://github.com/simonw/datasette/issues/1025#issuecomment-709632136

**Comment by simonw** [comment]
OK, this is definitely working now.

**Comment by tballison** [comment]
Just tested with the latest Docker image, and it works pretty much everywhere!  THANK YOU!

I did notice that if I try to export json or csv, the base is not applied.  Not sure if I should reopen this issue or open a new one.

To see this, go here: https://corpora.tika.apache.org/datasette/corpora-metadata/REF_PARSE_EXCEPTION_TYPES

Click/hover over json or CSV and you'll see that the 'datasette' base is not included.

Again, many thanks!

**Comment by tballison** [comment]
The same is true if I select advanced export and hit the 'export csv' at the bottom of the page.

**Comment by simonw** [comment]
@tballison thanks, I've split that out into a new issue #1091
