### ISSUE TITLE
Consider dropping explicit CSRF protection entirely?

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#877]
https://scotthelme.co.uk/csrf-is-dead/ from Feb 2017 has background here. The `SameSite=lax` cookie property effectively eliminates CSRF in modern browsers. https://caniuse.com/#search=SameSite shows 92.13% global support for it.

Datasette already uses `SameSite=lax` when it sets cookies by default: https://github.com/simonw/datasette/blob/af350ba4571b8e3f9708c40f2ddb48fea7ac1084/datasette/utils/asgi.py#L327-L341

A few options then. I could ditch CSRF protection entirely. I could make it optional - turn it off by default, but let users who care about that remaining 7.87% of global users opt back into it.

One catch: login CSRF: I don't see how `SameSite=lax` protects against that attack.

**Comment by simonw** [comment]
https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#login-csrf

> Login CSRF can be mitigated by creating pre-sessions (sessions before a user is authenticated) and including tokens in login form.

Sounds like regular CSRF protection to me.

**Comment by simonw** [comment]
Relevant: #835

**Comment by abdusco** [comment]
Does this mean custom routes get to expose endpoints accepting POST requests? I've tried earlier to add some POST endpoints, but requests were being rejected by Datasette due to CSRF

**Comment by simonw** [comment]
Have you tried the method described here? https://datasette.readthedocs.io/en/latest/internals.html#csrf-protection - I'm happy to bulk out that section of the documentation if that doesn't help solve your problem.

I just closed #835 which should make CSRF protection easier to work with - it won't intefere with requests without cookies or requests with `Authentication: Bearer token` tokens.

You can try out `pip install datasette==0.45a5` to get those features. Hopefully releasing a full 0.45 tomorrow.

**Comment by abdusco** [comment]
I am calling the API from another origin, so injecting CSRF token into template wouldn't work.

**Comment by abdusco** [comment]
Bearer tokens sound interesting? Where do tokens come from? An auth provider of my choosing? How do they get verified?

**Comment by simonw** [comment]
Tokens get verified by plugins. So far there's only one: https://github.com/simonw/datasette-auth-tokens - which has you hard-coding plugins in a configuration file. I have a issue there to add support for database-backed tokens too: https://github.com/simonw/datasette-auth-tokens/issues/1

**Comment by simonw** [comment]
The latest release of https://github.com/simonw/datasette-auth-tokens (0.2) now supports SQL configuration of tokens.

**Comment by simonw** [comment]
I'm not going to drop CSRF protection - it's still needed for older browsers - but I have relaxed the circumstances under which it is applied. It only applies to requests that include cookies for example, so API clients that don't send cookies don't need to worry about it.
