### ISSUE TITLE
Add NHS England Hospitals example to wiki

### ISSUE THREAD

**Issue by tomdyson** [simonw/datasette#88]
https://nhs-england-hospitals.now.sh

and an associated map visualisation:

http://run.plnkr.co/preview/cj9zlf1qc0003414y90ajkwpk/

Datasette is wonderful!

**Comment by simonw** [comment]
Hooray! First dataset that wasn't deployed by me :) https://github.com/simonw/datasette/wiki/Datasettes

**Comment by simonw** [comment]
I'm getting an internal server error on http://run.plnkr.co/preview/cj9zlf1qc0003414y90ajkwpk/ at the moment

**Comment by tomdyson** [comment]
> I'm getting an internal server error on http://run.plnkr.co/preview/cj9zlf1qc0003414y90ajkwpk/ at the moment

Sorry about that - here's a working version on Netlify:

https://nhs-england-map.netlify.com

**Comment by mroswell** [comment]
Google Map API limits seem to prevent https://nhs-england-map.netlify.com from being a working demo.
