### ISSUE TITLE
asgi_wrapper plugin hook is crashing at startup

### ISSUE THREAD

**Issue by amjith** [simonw/datasette#889]
Steps to reproduce: 

1. Install datasette-media plugin 
`pip install datasette-media`
2. Launch datasette
`datasette databasename.db`
3. Error

```
INFO:     Started server process [927704]
INFO:     Waiting for application startup.
ERROR:    Exception in 'lifespan' protocol
Traceback (most recent call last):
  File "/home/amjith/.virtualenvs/itsysearch/lib/python3.7/site-packages/uvicorn/lifespan/on.py", line 48, in main
    await app(scope, self.receive, self.send)
  File "/home/amjith/.virtualenvs/itsysearch/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/amjith/.virtualenvs/itsysearch/lib/python3.7/site-packages/datasette_media/__init__.py", line 9, in wrapped_app
    path = scope["path"]
KeyError: 'path'
ERROR:    Application startup failed. Exiting.
```

**Comment by amjith** [comment]
FWIW, this error does NOT happen in datasette 0.45a.

**Comment by amjith** [comment]
I was able to narrow this down to the fact that lifespan protocol is turned on. 

I see the workaround you've used here: https://github.com/simonw/datasette-debug-asgi/commit/72d568d32a3159c763ce908c0b269736935c6987

If so, maybe it's time to update some of the asg_wrapper [plugins](https://datasette.readthedocs.io/en/stable/plugin_hooks.html#asgi-wrapper-datasette).

**Comment by simonw** [comment]
Thanks - I've fixed this in `datasette-media` and the other plugins that use that hook now I think.
