### ISSUE TITLE
pip3 install datasette not serving static on linuxbrew.

### ISSUE THREAD

**Issue by zodman** [simonw/datasette#893]
*This error wasn't thrown*

```
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/opt/python@3.8/lib/python3.8/site-packages/datasette/utils/asgi.py", line 289, in inner_static
    full_path.relative_to(root_path)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.8/lib/python3.8/pathlib.py", line 904, in relative_to
    raise ValueError("{!r} does not start with {!r}"
ValueError: '/home/linuxbrew/.linuxbrew/lib/python3.8/site-packages/datasette/static/app.css' does not start with '/home/linuxbrew/.linuxbrew/opt/python@3.8/lib/python3.8/site-packages/datasette/static'
```

Linuxbrew install python@3.8 with symbolic links when  You call the full_path.relative_to(root_path) throw ValueError. This happened when you install from pip3

when you install with python3 setup.py develop , works good.

Well at the end the static wasn't serving.

**Comment by simonw** [comment]
I think I fixed this a while ago, though I can't find the commit now. Please re-open if the bug still happens!
