### ISSUE TITLE
Some links don't honor base_url

### ISSUE THREAD

**Issue by noteed** [simonw/datasette#900]
Hi,

I've been playing with Datasette behind Nginx (awesome tool, thanks !). It seems some URLs are OK but some aren't. For instance in https://github.com/simonw/datasette/blob/master/datasette/templates/query.html#L61 it seems that `url_csv` includes a `/` prefix, resulting in the `base_url` not beeing honored.

Actually here, it seems that dropping the prefix `/` to make the link relative is enough (so it may not be strictly related to `base_url`).

Additional information:

```
datasette, version 0.45+0.gf1f581b.dirty
```

Relevant Nginx configuration (note that all the trailing slashes have some effect):

```
  location /datasette/ {
    proxy_pass http://127.0.0.1:9001/;
    proxy_set_header Host $host;
  }
```

Relelvant Datasette configuration (slashes matter too):

```
  --config base_url:/datasette/
```

**Comment by simonw** [comment]
I think this is the same issue as #865. I'll look at these together!

**Comment by simonw** [comment]
Tracking ticket: #1023

**Comment by simonw** [comment]
I believe this particular bug has been fixed, based on my testing here: https://github.com/simonw/datasette/issues/1024#issuecomment-709622973

Please re-open the ticket if you are still experiencing it.
