### ISSUE TITLE
Travis should not build the master branch, only the main branch

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#919]
Caused by #849 - since we are mirroring the two branches (to ensure old links to `master` keep working) Travis is building both.

The following in `.travis.yml` should fix that:
```
branches:
  except:
  - master
```

**Comment by simonw** [comment]
That appears to have worked.

**Comment by stonebig** [comment]
a pypi wheel  ?

**Comment by simonw** [comment]
Should be released in a couple of minutes: https://travis-ci.org/github/simonw/datasette/builds/716328883
