### ISSUE TITLE
Try out CodeMirror SQL hints

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#949]
> It would also be interesting to try out the SQL hint mode, which can autocomplete against tables and columns. This demo shows how to configure that: https://codemirror.net/mode/sql/
> 
> Some missing documentation: https://stackoverflow.com/questions/20023381/codemirror-how-add-tables-to-sql-hint
_Originally posted by @simonw in https://github.com/simonw/datasette/issues/948#issuecomment-679355426_

**Comment by simonw** [comment]
I think this requires three extra files from https://github.com/codemirror/CodeMirror/tree/5.57.0/addon/hint

- `show-hint.css`
- `show-hint.js`
- `sql-hint.js`

**Comment by simonw** [comment]
I'm attracted to this because of how good GraphiQL is for auto-completing queries. But I realize there's a problem here: GraphQL is designed to be autocomplete-friendly, but SQL is not. If you type `select ` and it doesn't know what's going in the `from` clause it can't give you good column autocomplete, for example.

**Comment by simonw** [comment]
I'm not going to do any more work on this - SQL isn't an auto-complete friendly enough language.

**Comment by mhkeller** [comment]
FWIW, code mirror 6 now has this standard although if you want table-specific suggestions, you'd have to handle parsing out which table the user is querying yourself.

**Comment by simonw** [comment]
Datasette is using that now, see:
- #89
