### ISSUE TITLE
JSON arrays rather than array elements are used when search is applied

### ISSUE THREAD

**Issue by mhalle** [simonw/datasette#963]
Faceted search uses JSON array elements as facets rather than the arrays. However, if a search is "Apply"ed (using the Apply button), the array itself rather than its elements used. 

To reproduce:
https://latest.datasette.io/fixtures/facetable?_sort=pk&_facet=created&_facet=tags&_facet_array=tags

Press "Apply", which might be done when removing a filter. Notice that the "tags" facet values are now arrays, not array elements. It appears the "&_facet_array=tags" element of the query string is dropped.

**Comment by simonw** [comment]
Good bug - looks like a problem with the hidden form fields.
