### ISSUE TITLE
Link to JSON for the list of tables 

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#97]
https://twitter.com/yschimke/status/930606210855854080

**Comment by yschimke** [comment]
Specifically docs should make it clearer this file exists

https://parlgov.datasettes.com/.json

And from that you can build https://parlgov.datasettes.com/parlgov-25f9855.json

Then https://parlgov.datasettes.com/parlgov-25f9855/cabinet.json

**Comment by simonw** [comment]
The `/.json` endpoint is more of an implementation detail of the homepage at this point. A better, documented ( http://datasette.readthedocs.io/en/stable/introspection.html#inspect ) endpoint for finding all of the databases and tables is https://parlgov.datasettes.com/-/inspect.json

**Comment by yschimke** [comment]
Do you have an existing example with views?
