### ISSUE TITLE
request an "-o" option on "datasette server" to open the default browser at the running url

### ISSUE THREAD

**Issue by secretGeek** [simonw/datasette#970]
This is a request for a "convenience" feature, and only a nice to have. It's based on seeing this feature in several little command line hypertext server apps.

If you run, for example:

    datasette.exe serve --open "mydb.s3db" 

I would like it if default browser is launched, at the URL that is being served.

The angular cli does this, for example 

  ng serve <project> --open  #see https://angular.io/cli/serve

...as does my usual mini web server of choice when inspecting local static files....

  npx http-server -o # see https://www.npmjs.com/package/http-server

Just a tiny thing. Love your work!

**Comment by simonw** [comment]
I like this. It could work with the `--root` option too and automatically sign you in as the root user.

**Comment by simonw** [comment]
The Python standard library has a module for this: https://docs.python.org/3/library/webbrowser.html

**Comment by secretGeek** [comment]
Oh wow oh wow. Thanks so much Simon. In an astoundingly rough week, this is a shining jewel. 🤣

**Comment by simonw** [comment]
Idea: if a database only has a single table, this could open straight to `/db/table`. If it has multiple tables but a single databsae it could open straight to `/db`.
