### ISSUE TITLE
Wide tables should scroll horizontally within the page

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#998]
Wrap the main table in `<div style="overflow-x: auto">`

**Comment by simonw** [comment]
I tried this out and it did cause one problem with plugins: `datasette-cluster-map` still injected itself inside the scrolling area, when instead we would want that map to stay outside of the div with the table in it.

**Comment by simonw** [comment]
So maybe this is blocked on #987 and adding a new hook in the HTML which plugins like `datasette-cluster-map` can attach their content to.

**Comment by simonw** [comment]
This may require updates to the column action menu JavaScript too, since it was not built with scrolling sideways in mind.

**Comment by simonw** [comment]
Easiest fix for the column action menu positioning - hide them when the user scrolls the containing div:
```javascript
document.querySelector('.table-wrapper').addEventListener(
  'scroll', () => document.querySelector('.dropdown-menu').style.display = 'none'
);                                            
```

**Comment by simonw** [comment]
This isn't blocked on #987 - it just means that `datasette-cluster-map` will need to learn to look for `.table-wrapper` first and fall back on the table.

**Comment by simonw** [comment]
Demo:
![table-scroll](https://user-images.githubusercontent.com/9599/96806421-e74e7e00-13c8-11eb-95fe-44d01e4c2eb3.gif)

**Comment by simonw** [comment]
This is now live here: https://global-power-plants.datasettes.com/global-power-plants/global-power-plants

**Comment by JBPressac** [comment]
Hello Simon,
I have a similar problem with horizontal scrollbar display with Datasette version 0.51 and superior for a table with more than 30 rows. With Datasette 0.50, the horizontal scrollbar is displayed, if I upgrade Datasette to 0.51 and superior, the horizontal scrollbar disappears.

Datasette 0.50: horizontal scrollbar

![2020-12-11 10_23_28-CN=Microsoft Windows, O=Microsoft Corporation, L=Redmond, S=Washington, C=US](https://user-images.githubusercontent.com/6371750/101885620-a5f17800-3b9a-11eb-8870-654e7d4372ca.png)

Datasette 0.51 and superior: no horizontal scrollbar

![2020-12-11 10_24_55-CN=Microsoft Windows, O=Microsoft Corporation, L=Redmond, S=Washington, C=US](https://user-images.githubusercontent.com/6371750/101885782-dfc27e80-3b9a-11eb-9d55-6c9a56227bf2.png)

Thanks,
